In [23]:
import os
import pandas as pd

Prepare 2022 PISA Dataset

In [24]:
pisa2022_df = pd.read_sas(r"C:\1stApril\Work\4rd_Year\4rd2\CSS400_Project_Development\cy08msp_stu_qqq.sas7bdat", encoding='cp1252')
pisa2022_df

,CNT,CNTRYID,CNTSCHID,CNTSTUID,CYC,NatCen,STRATUM,SUBNATIO,REGION,OECD,...,PV4MPRE,PV5MPRE,PV6MPRE,PV7MPRE,PV8MPRE,PV9MPRE,PV10MPRE,SENWT,VER_DAT,i
0,ALB,8.0,800282.0,800001.0,08MS,000800,ALB03,0080000,800.0,0.0,...,203.029,219.817,331.017,223.752,305.671,230.156,289.436,0.55561,03MAY23:10:11:25,218.0
1,ALB,8.0,800115.0,800002.0,08MS,000800,ALB03,0080000,800.0,0.0,...,321.405,320.452,284.836,364.565,304.044,347.626,352.269,0.76431,03MAY23:10:11:25,218.0
2,ALB,8.0,800242.0,800003.0,08MS,000800,ALB01,0080000,800.0,0.0,...,376.019,285.901,289.896,338.469,316.296,324.361,343.351,1.37877,03MAY23:10:11:25,218.0
3,ALB,8.0,800245.0,800005.0,08MS,000800,ALB08,0080000,800.0,0.0,...,303.422,327.793,165.575,246.156,238.322,275.860,227.466,1.49361,03MAY23:10:11:26,218.0
4,ALB,8.0,800285.0,800006.0,08MS,000800,ALB03,0080000,800.0,0.0,...,514.739,539.850,461.793,514.465,510.462,490.537,503.793,0.65249,03MAY23:10:11:26,218.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
613739,UZB,860.0,86000120.0,86007488.0,08MS,086000,UZB26,8600000,86000.0,0.0,...,306.551,271.135,386.969,376.271,368.287,395.329,278.263,0.71987,02MAY23:13:18:15,218.0
613740,UZB,860.0,86000140.0,86007489.0,08MS,086000,UZB04,8600000,86000.0,0.0,...,335.952,232.583,179.328,233.470,203.001,254.340,233.187,0.65541,02MAY23:13:18:13,218.0
613741,UZB,860.0,86000024.0,86007490.0,08MS,086000,UZB10,8600000,86000.0,0.0,...,451.614,432.586,387.329,456.236,424.790,408.986,460.542,0.67910,02MAY23:13:18:13,218.0
613742,UZB,860.0,86000174.0,86007491.0,08MS,086000,UZB16,8600000,86000.0,0.0,...,272.346,317.838,248.165,405.860,364.173,346.663,341.668,0.68618,02MAY23:13:18:14,218.0
613743,UZB,860.0,86000123.0,86007492.0,08MS,086000,UZB10,8600000,86000.0,0.0,...,416.631,337.422,370.817,395.176,412.317,390.490,439.211,0.67910,02MAY23:13:18:13,218.0

In [25]:
pisa2022_df.dtypes

CNT              object
CNTRYID         float64
CNTSCHID        float64
CNTSTUID        float64
CYC              object
NatCen           object
STRATUM          object
SUBNATIO         object
REGION          float64
OECD            float64
ADMINMODE       float64
LANGTEST_QQQ    float64
LANGTEST_COG    float64
LANGTEST_PAQ    float64
Option_CT       float64
Option_FL       float64
Option_ICTQ     float64
Option_WBQ      float64
Option_PQ       float64
Option_TQ       float64
Option_UH       float64
BOOKID          float64
ST001D01T       float64
ST003D02T       float64
ST003D03T       float64
ST004D01T       float64
ST250Q01JA      float64
ST250Q02JA      float64
ST250Q03JA      float64
ST250Q04JA      float64
ST250Q05JA      float64
ST250D06JA       object
ST250D07JA       object
ST251Q01JA      float64
ST251Q02JA      float64
ST251Q03JA      float64
ST251Q04JA      float64
ST251Q06JA      float64
ST251Q07JA      float64
ST251D08JA       object
ST251D09JA       object
ST253Q01JA      float64
ST254Q01JA      float64
ST254Q02JA      float64
ST254Q03JA      float64
ST254Q04JA      float64
ST254Q05JA      float64
ST254Q06JA      float64
ST255Q01JA      float64
ST256Q01JA      float64
ST256Q02JA      float64
ST256Q03JA      float64
ST256Q06JA      float64
ST256Q07JA      float64
ST256Q08JA      float64
ST256Q09JA      float64
ST256Q10JA      float64
ST230Q01JA      float64
ST005Q01JA      float64
ST006Q01JA      float64
ST006Q02JA      float64
ST006Q03JA      float64
ST006Q04JA      float64
ST006Q05JA      float64
ST007Q01JA      float64
ST008Q01JA      float64
ST008Q02JA      float64
ST008Q03JA      float64
ST008Q04JA      float64
ST008Q05JA      float64
ST258Q01JA      float64
ST259Q01JA      float64
ST259Q02JA      float64
ST019AQ01T      float64
ST019BQ01T      float64
ST019CQ01T      float64
ST021Q01TA      float64
ST022Q01TA      float64
ST226Q01JA      float64
ST125Q01NA      float64
ST126Q01TA      float64
ST127Q01TA      float64
ST127Q02TA      float64
ST127Q03TA      float64
ST260Q01JA      float64
ST260Q02JA      float64
ST260Q03JA      float64
ST261Q01JA      float64
ST261Q02JA      float64
ST261Q03JA      float64
ST261Q04JA      float64
ST261Q05JA      float64
ST261Q06JA      float64
ST261Q07JA      float64
ST261Q08JA      float64
ST261Q09JA      float64
ST261Q10JA      float64
ST261Q11JA      float64
ST062Q01TA      float64
ST062Q02TA      float64
ST062Q03TA      float64
ST267Q01JA      float64
ST267Q02JA      float64
ST267Q03JA      float64
ST267Q04JA      float64
ST267Q05JA      float64
ST267Q06JA      float64
ST267Q07JA      float64
ST267Q08JA      float64
ST034Q01TA      float64
ST034Q02TA      float64
ST034Q03TA      float64
ST034Q04TA      float64
ST034Q05TA      float64
ST034Q06TA      float64
ST038Q03NA      float64
ST038Q04NA      float64
ST038Q05NA      float64
ST038Q06NA      float64
ST038Q07NA      float64
ST038Q08NA      float64
ST038Q09JA      float64
ST038Q10JA      float64
ST038Q11JA      float64
ST265Q01JA      float64
ST265Q02JA      float64
ST265Q03JA      float64
ST265Q04JA      float64
ST266Q01JA      float64
ST266Q02JA      float64
ST266Q03JA      float64
ST266Q04JA      float64
ST266Q05JA      float64
ST294Q01JA      float64
ST294Q02JA      float64
ST294Q03JA      float64
ST294Q04JA      float64
ST294Q05JA      float64
ST295Q01JA      float64
ST295Q02JA      float64
ST295Q03JA      float64
ST295Q04JA      float64
ST295Q05JA      float64
ST326Q01JA      float64
ST326Q02JA      float64
ST326Q03JA      float64
ST326Q04JA      float64
ST326Q05JA      float64
ST326Q06JA      float64
ST326Q07JA      float64
ST326Q08JA      float64
ST326Q09JA      float64
ST326Q10JA      float64
ST326Q11JA      float64
ST326Q12JA      float64
ST322Q01JA      float64
ST322Q02JA      float64
ST322Q03JA      float64
ST322Q04JA      float64
ST322Q06JA      float64
ST322Q07JA      float64
ST307Q01JA      float64
ST307Q02JA      float64
ST307Q03JA      float64
ST307Q04JA      float64
ST307Q05JA      float64
ST307Q06JA      float64
ST307Q07JA      float64
ST307Q08JA      float64
ST307Q09JA      float64
ST307Q10JA      float64
ST309Q01JA      float64
ST309Q02JA      float64
ST309Q03JA      float64
ST309Q04JA      float64
ST309Q05JA      float64
ST309Q06JA      float64
ST309Q07JA      float64
ST309Q08JA      float64
ST309Q09JA      float64
ST309Q10JA      float64
ST301Q01JA      float64
ST301Q02JA      float64
ST301Q03JA      float64
ST301Q04JA      float64
ST301Q05JA      float64
ST301Q06JA      float64
ST301Q07JA      float64
ST301Q08JA      float64
ST301Q09JA      float64
ST301Q10JA      float64
ST343Q01JA      float64
ST343Q02JA      float64
ST343Q03JA      float64
ST343Q04JA      float64
ST343Q05JA      float64
ST343Q06JA      float64
ST343Q07JA      float64
ST343Q08JA      float64
ST343Q09JA      float64
ST343Q10JA      float64
ST311Q01JA      float64
ST311Q02JA      float64
ST311Q03JA      float64
ST311Q04JA      float64
ST311Q05JA      float64
ST311Q06JA      float64
ST311Q07JA      float64
ST311Q08JA      float64
ST311Q09JA      float64
ST311Q10JA      float64
ST315Q01JA      float64
ST315Q02JA      float64
ST315Q03JA      float64
ST315Q04JA      float64
ST315Q05JA      float64
ST315Q06JA      float64
ST315Q07JA      float64
ST315Q08JA      float64
ST315Q09JA      float64
ST315Q10JA      float64
ST303Q01JA      float64
ST303Q02JA      float64
ST303Q03JA      float64
ST303Q04JA      float64
ST303Q05JA      float64
ST303Q06JA      float64
ST303Q07JA      float64
ST303Q08JA      float64
ST305Q01JA      float64
ST305Q02JA      float64
ST305Q03JA      float64
ST305Q04JA      float64
ST305Q05JA      float64
ST305Q06JA      float64
ST305Q07JA      float64
ST305Q08JA      float64
ST305Q09JA      float64
ST305Q10JA      float64
ST345Q01JA      float64
ST345Q02JA      float64
ST345Q03JA      float64
ST345Q04JA      float64
ST345Q05JA      float64
ST345Q06JA      float64
ST345Q07JA      float64
ST345Q08JA      float64
ST345Q09JA      float64
ST345Q10JA      float64
ST313Q01JA      float64
ST313Q02JA      float64
ST313Q03JA      float64
ST313Q04JA      float64
ST313Q05JA      float64
ST313Q06JA      float64
ST313Q07JA      float64
ST313Q08JA      float64
ST313Q09JA      float64
ST313Q10JA      float64
ST263Q02JA      float64
ST263Q04JA      float64
ST263Q06JA      float64
ST263Q08JA      float64
ST016Q01NA      float64
ST059Q01TA      float64
ST059Q02JA      float64
ST296Q01JA      float64
ST296Q02JA      float64
ST296Q03JA      float64
ST296Q04JA      float64
ST272Q01JA      float64
ST273Q01JA      float64
ST273Q02JA      float64
ST273Q03JA      float64
ST273Q04JA      float64
ST273Q05JA      float64
ST273Q06JA      float64
ST273Q07JA      float64
ST270Q01JA      float64
ST270Q02JA      float64
ST270Q03JA      float64
ST270Q04JA      float64
ST285Q01JA      float64
ST285Q02JA      float64
ST285Q03JA      float64
ST285Q04JA      float64
ST285Q05JA      float64
ST285Q06JA      float64
ST285Q07JA      float64
ST285Q08JA      float64
ST285Q09JA      float64
ST283Q01JA      float64
ST283Q02JA      float64
ST283Q03JA      float64
ST283Q04JA      float64
ST283Q05JA      float64
ST283Q06JA      float64
ST283Q07JA      float64
ST283Q08JA      float64
ST283Q09JA      float64
ST275Q01WA      float64
ST275Q02WA      float64
ST275Q03WA      float64
ST275Q04WA      float64
ST275Q05WA      float64
ST275Q06WA      float64
ST275Q07WA      float64
ST275Q08WA      float64
ST275Q09WA      float64
ST276Q01JA      float64
ST276Q02JA      float64
ST276Q03JA      float64
ST276Q04JA      float64
ST276Q05JA      float64
ST276Q06JA      float64
ST276Q07JA      float64
ST276Q08JA      float64
ST276Q09JA      float64
ST276Q10JA      float64
ST268Q01JA      float64
ST268Q02JA      float64
ST268Q03JA      float64
ST268Q04JA      float64
ST268Q05JA      float64
ST268Q06JA      float64
ST268Q07JA      float64
ST268Q08JA      float64
ST268Q09JA      float64
ST290Q01WA      float64
ST290Q02WA      float64
ST290Q03WA      float64
ST290Q04WA      float64
ST290Q05WA      float64
ST290Q06WA      float64
ST290Q07WA      float64
ST290Q08WA      float64
ST290Q09WA      float64
ST291Q01JA      float64
ST291Q02JA      float64
ST291Q03JA      float64
ST291Q04JA      float64
ST291Q05JA      float64
ST291Q06JA      float64
ST291Q07JA      float64
ST291Q08JA      float64
ST291Q09JA      float64
ST291Q10JA      float64
ST289Q01WA      float64
ST289Q02JA      float64
ST289Q03WA      float64
ST289Q04JA      float64
ST289Q05WA      float64
ST289Q06JA      float64
ST289Q07JA      float64
ST289Q08WA      float64
ST289Q09WA      float64
ST289Q10WA      float64
ST289Q11WA      float64
ST289Q14JA      float64
ST293Q01JA      float64
ST293Q02JA      float64
ST293Q03JA      float64
ST293Q04JA      float64
ST293Q05JA      float64
ST293Q06JA      float64
ST293Q07JA      float64
ST293Q08JA      float64
ST293Q09JA      float64
ST292Q01JA      float64
ST292Q02JA      float64
ST292Q03JA      float64
ST292Q04JA      float64
ST292Q05JA      float64
ST292Q06JA      float64
ST297Q01JA      float64
ST297Q03JA      float64
ST297Q05JA      float64
ST297Q06JA      float64
ST297Q07JA      float64
ST297Q09JA      float64
ST334Q01JA      float64
ST334Q02JA      float64
ST334Q03JA      float64
ST334Q04JA      float64
ST334Q05JA      float64
ST334Q06JA      float64
ST334Q07JA      float64
ST334Q08JA      float64
ST334Q09JA      float64
ST334Q10JA      float64
ST335Q01JA      float64
ST335Q02JA      float64
ST335Q03JA      float64
ST335Q05JA      float64
ST335Q06JA      float64
ST335Q07JA      float64
ST336Q01JA      float64
ST336Q03JA      float64
ST336Q04JA      float64
ST336Q05JA      float64
ST336Q06JA      float64
ST336Q07JA      float64
ST337Q01JA      float64
ST337Q02JA      float64
ST337Q03JA      float64
ST337Q04JA      float64
ST337Q05JA      float64
ST337Q06JA      float64
ST337Q07JA      float64
ST337Q08JA      float64
ST338Q01JA      float64
ST338Q02JA      float64
ST338Q03JA      float64
ST338Q04JA      float64
ST338Q05JA      float64
ST338Q06JA      float64
ST338Q07JA      float64
ST338Q08JA      float64
ST339Q04JA      float64
ST339Q06JA      float64
ST340Q01JA      float64
ST340Q02JA      float64
ST340Q03JA      float64
ST340Q04JA      float64
ST340Q05JA      float64
ST340Q06JA      float64
ST340Q07JA      float64
ST340Q08JA      float64
ST340Q09JA      float64
ST340Q10JA      float64
ST341Q01JA      float64
ST341Q02JA      float64
ST341Q03JA      float64
ST341Q04JA      float64
ST341Q05JA      float64
ST342Q01JA      float64
ST342Q02JA      float64
ST342Q03JA      float64
ST342Q04JA      float64
ST342Q06JA      float64
ST342Q07JA      float64
ST342Q08JA      float64
ST300Q01JA      float64
ST300Q02JA      float64
ST300Q03JA      float64
ST300Q04JA      float64
ST300Q05JA      float64
ST300Q06JA      float64
ST300Q07JA      float64
ST300Q08JA      float64
ST300Q09JA      float64
ST300Q10JA      float64
ST327Q01JA      float64
ST327Q02JA      float64
ST327Q03JA      float64
ST327Q04JA      float64
ST327Q05JA      float64
ST327Q06JA      float64
ST327Q07JA      float64
ST327Q08JA      float64
ST330Q01WA      float64
ST330Q02WA      float64
ST330Q03WA      float64
ST330Q04WA      float64
ST330Q05WA      float64
ST330Q06WA      float64
ST330Q07WA      float64
ST330Q08WA      float64
ST330Q09WA      float64
ST330Q11WA      float64
ST330D10WA       object
ST324Q02JA      float64
ST324Q04JA      float64
ST324Q05JA      float64
ST324Q07JA      float64
ST324Q10JA      float64
ST324Q11JA      float64
ST324Q12JA      float64
ST324Q13JA      float64
ST324Q14JA      float64
ST347Q01JA      float64
ST347Q02JA      float64
ST348Q01JA      float64
ST348Q02JA      float64
ST348Q03JA      float64
ST348Q04JA      float64
ST348Q05JA      float64
ST348Q06JA      float64
ST348Q07JA      float64
ST348Q08JA      float64
ST349Q01JA      float64
ST350Q01JA      float64
ST351Q01JA      float64
ST351Q02JA      float64
ST351Q03JA      float64
ST351Q04JA      float64
ST351Q05JA      float64
ST351Q06JA      float64
ST351Q07JA      float64
ST351Q08JA      float64
ST352Q01JA      float64
ST352Q02JA      float64
ST352Q03JA      float64
ST352Q04JA      float64
ST352Q05JA      float64
ST352Q06JA      float64
ST352Q07JA      float64
ST352Q08JA      float64
ST353Q01JA      float64
ST353Q02JA      float64
ST353Q03JA      float64
ST353Q04JA      float64
ST353Q05JA      float64
ST353Q06JA      float64
ST353Q07JA      float64
ST353Q08JA      float64
ST354Q01JA      float64
ST354Q02JA      float64
ST354Q03JA      float64
ST354Q04JA      float64
ST354Q05JA      float64
ST354Q06JA      float64
ST354Q07JA      float64
ST354Q08JA      float64
ST354Q09JA      float64
ST354Q10JA      float64
ST355Q01JA      float64
ST355Q02JA      float64
ST355Q03JA      float64
ST355Q04JA      float64
ST355Q05JA      float64
ST355Q06JA      float64
ST355Q07JA      float64
ST355Q08JA      float64
ST356Q01JA      float64
ST331Q01JA      float64
ST331Q02JA      float64
ST331Q03JA      float64
FL150Q01TA      float64
FL150Q02TA      float64
FL150Q03TA      float64
FL164Q01HA      float64
FL164Q02HA      float64
FL164Q03HA      float64
FL164Q04HA      float64
FL164Q05HA      float64
FL164Q06HA      float64
FL164Q07HA      float64
FL164Q08HA      float64
FL164Q09HA      float64
FL164Q10HA      float64
FL164Q11HA      float64
FL164Q12HA      float64
FL164Q13HA      float64
FL164Q14HA      float64
FL164Q15HA      float64
FL164Q16HA      float64
FL166Q01HA      float64
FL166Q02HA      float64
FL166Q03HA      float64
FL166Q05HA      float64
FL166Q06HA      float64
FL166Q07HA      float64
FL174Q01JA      float64
FL174Q02JA      float64
FL174Q03JA      float64
FL174Q04JA      float64
FL174Q05JA      float64
FL174Q06JA      float64
FL174Q07JA      float64
FL167Q01HA      float64
FL167Q02HA      float64
FL167Q06JA      float64
FL167Q03HA      float64
FL167Q04HA      float64
FL167Q05HA      float64
FL167Q07JA      float64
FL170Q01JA      float64
FL170Q02JA      float64
FL170Q03JA      float64
FL170Q04JA      float64
FL170Q05JA      float64
FL170Q06JA      float64
FL170Q07JA      float64
FL159Q01HA      float64
FL159Q02HA      float64
FL159Q03HA      float64
FL159Q04HA      float64
FL160Q01HA      float64
FL160Q02HA      float64
FL160Q03HA      float64
FL160Q04HA      float64
FL161Q01HA      float64
FL161Q02HA      float64
FL161Q03HA      float64
FL162Q01HA      float64
FL162Q02HA      float64
FL162Q03HA      float64
FL162Q04HA      float64
FL162Q05HA      float64
FL162Q06HA      float64
FL163Q01HA      float64
FL163Q02HA      float64
FL163Q03HA      float64
FL163Q04HA      float64
FL163Q05HA      float64
FL171Q01JA      float64
FL171Q02JA      float64
FL171Q03JA      float64
FL171Q04JA      float64
FL171Q05JA      float64
FL171Q07JA      float64
FL171Q08JA      float64
FL171Q09JA      float64
FL171Q10JA      float64
FL171Q11JA      float64
FL171Q12JA      float64
FL169Q01HA      float64
FL169Q05JA      float64
FL169Q02HA      float64
FL169Q06JA      float64
FL169Q07JA      float64
FL169Q03HA      float64
FL169Q04HA      float64
FL169Q08JA      float64
FL169Q10JA      float64
FL169Q11JA      float64
FL172Q01JA      float64
FL172Q03JA      float64
FL172Q05JA      float64
FL172Q06JA      float64
IC170Q01JA      float64
IC170Q02JA      float64
IC170Q03JA      float64
IC170Q04JA      float64
IC170Q05JA      float64
IC170Q06JA      float64
IC170Q07JA      float64
IC171Q01JA      float64
IC171Q02JA      float64
IC171Q03JA      float64
IC171Q04JA      float64
IC171Q05JA      float64
IC171Q06JA      float64
IC172Q01JA      float64
IC172Q02JA      float64
IC172Q03JA      float64
IC172Q04JA      float64
IC172Q05JA      float64
IC172Q06JA      float64
IC172Q07JA      float64
IC172Q08JA      float64
IC172Q09JA      float64
IC173Q01JA      float64
IC173Q02JA      float64
IC173Q03JA      float64
IC173Q04JA      float64
IC174Q01JA      float64
IC174Q02JA      float64
IC174Q03JA      float64
IC174Q04JA      float64
IC174Q05JA      float64
IC174Q06JA      float64
IC174Q07JA      float64
IC174Q08JA      float64
IC174Q09JA      float64
IC174Q10JA      float64
IC175Q01JA      float64
IC175Q02JA      float64
IC175Q03JA      float64
IC175Q05JA      float64
IC176Q01JA      float64
IC176Q02JA      float64
IC176Q03JA      float64
IC176Q04JA      float64
IC176Q05JA      float64
IC176Q06JA      float64
IC176Q07JA      float64
IC176Q08JA      float64
IC184Q01JA      float64
IC184Q02JA      float64
IC184Q03JA      float64
IC184Q04JA      float64
IC177Q01JA      float64
IC177Q02JA      float64
IC177Q03JA      float64
IC177Q04JA      float64
IC177Q05JA      float64
IC177Q06JA      float64
IC177Q07JA      float64
IC178Q01JA      float64
IC178Q02JA      float64
IC178Q03JA      float64
IC178Q04JA      float64
IC178Q05JA      float64
IC178Q06JA      float64
IC178Q07JA      float64
IC179Q01JA      float64
IC179Q02JA      float64
IC179Q03JA      float64
IC179Q04JA      float64
IC179Q05JA      float64
IC179Q06JA      float64
IC180Q01JA      float64
IC180Q02JA      float64
IC180Q03JA      float64
IC180Q04JA      float64
IC180Q05JA      float64
IC180Q06JA      float64
IC180Q07JA      float64
IC180Q08JA      float64
IC181Q01JA      float64
IC181Q02JA      float64
IC181Q03JA      float64
IC181Q04JA      float64
IC182Q01JA      float64
IC182Q02JA      float64
IC182Q03JA      float64
IC183Q01JA      float64
IC183Q02JA      float64
IC183Q03JA      float64
IC183Q04JA      float64
IC183Q05JA      float64
IC183Q07JA      float64
IC183Q08JA      float64
IC183Q09JA      float64
IC183Q10JA      float64
IC183Q12JA      float64
IC183Q13JA      float64
IC183Q14JA      float64
IC183Q15JA      float64
IC183Q16JA      float64
WB150Q01HA      float64
WB151Q01HA      float64
WB152Q01HA      float64
WB153Q01HA      float64
WB153Q02HA      float64
WB153Q03HA      float64
WB153Q04HA      float64
WB153Q05HA      float64
WB154Q01HA      float64
WB154Q02HA      float64
WB154Q03HA      float64
WB154Q04HA      float64
WB154Q05HA      float64
WB154Q06HA      float64
WB154Q07HA      float64
WB154Q08HA      float64
WB154Q09HA      float64
WB155Q01HA      float64
WB155Q02HA      float64
WB155Q03HA      float64
WB155Q04HA      float64
WB155Q05HA      float64
WB155Q06HA      float64
WB155Q07HA      float64
WB155Q08HA      float64
WB155Q09HA      float64
WB155Q10HA      float64
WB156Q01HA      float64
WB158Q01HA      float64
WB160Q01HA      float64
WB161Q01HA      float64
WB162Q01HA      float64
WB162Q02HA      float64
WB162Q03HA      float64
WB162Q04HA      float64
WB162Q05HA      float64
WB162Q06HA      float64
WB162Q07HA      float64
WB162Q08HA      float64
WB162Q09HA      float64
WB163Q01HA      float64
WB163Q02HA      float64
WB163Q03HA      float64
WB163Q04HA      float64
WB163Q05HA      float64
WB163Q06HA      float64
WB163Q07HA      float64
WB163Q08HA      float64
WB164Q01HA      float64
WB165Q01HA      float64
WB166Q01HA      float64
WB166Q02HA      float64
WB166Q03HA      float64
WB166Q04HA      float64
WB167Q01HA      float64
WB168Q01HA      float64
WB168Q02HA      float64
WB168Q03HA      float64
WB168Q04HA      float64
WB171Q01HA      float64
WB171Q02HA      float64
WB171Q03HA      float64
WB171Q04HA      float64
WB172Q01HA      float64
WB173Q01HA      float64
WB173Q02HA      float64
WB173Q03HA      float64
WB173Q04HA      float64
WB176Q01HA      float64
WB177Q01HA      float64
WB177Q02HA      float64
WB177Q03HA      float64
WB177Q04HA      float64
WB032Q01NA      float64
WB032Q02NA      float64
WB031Q01NA      float64
WB178Q01HA      float64
WB178Q02HA      float64
WB178Q03HA      float64
WB178Q04HA      float64
WB178Q05HA      float64
WB178Q06HA      float64
WB178Q07HA      float64
PA001Q01TA      float64
PA001Q02TA      float64
PA001Q03TA      float64
PA003Q01TA      float64
PA003Q02TA      float64
PA003Q03TA      float64
PA003Q05IA      float64
PA003Q18WA      float64
PA003Q19WA      float64
PA003Q20WA      float64
PA003Q11JA      float64
PA003Q12JA      float64
PA003Q13JA      float64
PA003Q14JA      float64
PA003Q15JA      float64
PA003Q16JA      float64
PA003Q17JA      float64
PA196Q01WA      float64

In [26]:
replacements = {
    'object' : 'varchar(20)',
    'float64' : 'float',
    'init64' : 'int',
    'datetime64': 'timestamp'
}

In [27]:
col_str = ", ".join("{} {}".format(n,d) for (n,d) in zip(pisa2022_df.columns, pisa2022_df.dtypes.replace(replacements)))
col_str

'CNT varchar(20), CNTRYID float, CNTSCHID float, CNTSTUID float, CYC varchar(20), NatCen varchar(20), STRATUM varchar(20), SUBNATIO varchar(20), REGION float, OECD float, ADMINMODE float, LANGTEST_QQQ float, LANGTEST_COG float, LANGTEST_PAQ float, Option_CT float, Option_FL float, Option_ICTQ float, Option_WBQ float, Option_PQ float, Option_TQ float, Option_UH float, BOOKID float, ST001D01T float, ST003D02T float, ST003D03T float, ST004D01T float, ST250Q01JA float, ST250Q02JA float, ST250Q03JA float, ST250Q04JA float, ST250Q05JA float, ST250D06JA varchar(20), ST250D07JA varchar(20), ST251Q01JA float, ST251Q02JA float, ST251Q03JA float, ST251Q04JA float, ST251Q06JA float, ST251Q07JA float, ST251D08JA varchar(20), ST251D09JA varchar(20), ST253Q01JA float, ST254Q01JA float, ST254Q02JA float, ST254Q03JA float, ST254Q04JA float, ST254Q05JA float, ST254Q06JA float, ST255Q01JA float, ST256Q01JA float, ST256Q02JA float, ST256Q03JA float, ST256Q06JA float, ST256Q07JA float, ST256Q08JA float, ST256Q09JA float, ST256Q10JA float, ST230Q01JA float, ST005Q01JA float, ST006Q01JA float, ST006Q02JA float, ST006Q03JA float, ST006Q04JA float, ST006Q05JA float, ST007Q01JA float, ST008Q01JA float, ST008Q02JA float, ST008Q03JA float, ST008Q04JA float, ST008Q05JA float, ST258Q01JA float, ST259Q01JA float, ST259Q02JA float, ST019AQ01T float, ST019BQ01T float, ST019CQ01T float, ST021Q01TA float, ST022Q01TA float, ST226Q01JA float, ST125Q01NA float, ST126Q01TA float, ST127Q01TA float, ST127Q02TA float, ST127Q03TA float, ST260Q01JA float, ST260Q02JA float, ST260Q03JA float, ST261Q01JA float, ST261Q02JA float, ST261Q03JA float, ST261Q04JA float, ST261Q05JA float, ST261Q06JA float, ST261Q07JA float, ST261Q08JA float, ST261Q09JA float, ST261Q10JA float, ST261Q11JA float, ST062Q01TA float, ST062Q02TA float, ST062Q03TA float, ST267Q01JA float, ST267Q02JA float, ST267Q03JA float, ST267Q04JA float, ST267Q05JA float, ST267Q06JA float, ST267Q07JA float, ST267Q08JA float, ST034Q01TA float, ST034Q02TA float, ST034Q03TA float, ST034Q04TA float, ST034Q05TA float, ST034Q06TA float, ST038Q03NA float, ST038Q04NA float, ST038Q05NA float, ST038Q06NA float, ST038Q07NA float, ST038Q08NA float, ST038Q09JA float, ST038Q10JA float, ST038Q11JA float, ST265Q01JA float, ST265Q02JA float, ST265Q03JA float, ST265Q04JA float, ST266Q01JA float, ST266Q02JA float, ST266Q03JA float, ST266Q04JA float, ST266Q05JA float, ST294Q01JA float, ST294Q02JA float, ST294Q03JA float, ST294Q04JA float, ST294Q05JA float, ST295Q01JA float, ST295Q02JA float, ST295Q03JA float, ST295Q04JA float, ST295Q05JA float, ST326Q01JA float, ST326Q02JA float, ST326Q03JA float, ST326Q04JA float, ST326Q05JA float, ST326Q06JA float, ST326Q07JA float, ST326Q08JA float, ST326Q09JA float, ST326Q10JA float, ST326Q11JA float, ST326Q12JA float, ST322Q01JA float, ST322Q02JA float, ST322Q03JA float, ST322Q04JA float, ST322Q06JA float, ST322Q07JA float, ST307Q01JA float, ST307Q02JA float, ST307Q03JA float, ST307Q04JA float, ST307Q05JA float, ST307Q06JA float, ST307Q07JA float, ST307Q08JA float, ST307Q09JA float, ST307Q10JA float, ST309Q01JA float, ST309Q02JA float, ST309Q03JA float, ST309Q04JA float, ST309Q05JA float, ST309Q06JA float, ST309Q07JA float, ST309Q08JA float, ST309Q09JA float, ST309Q10JA float, ST301Q01JA float, ST301Q02JA float, ST301Q03JA float, ST301Q04JA float, ST301Q05JA float, ST301Q06JA float, ST301Q07JA float, ST301Q08JA float, ST301Q09JA float, ST301Q10JA float, ST343Q01JA float, ST343Q02JA float, ST343Q03JA float, ST343Q04JA float, ST343Q05JA float, ST343Q06JA float, ST343Q07JA float, ST343Q08JA float, ST343Q09JA float, ST343Q10JA float, ST311Q01JA float, ST311Q02JA float, ST311Q03JA float, ST311Q04JA float, ST311Q05JA float, ST311Q06JA float, ST311Q07JA float, ST311Q08JA float, ST311Q09JA float, ST311Q10JA float, ST315Q01JA float, ST315Q02JA float, ST315Q03JA float, ST315Q04JA float, ST315Q05JA float, ST315Q06JA float, ST315Q07JA float, ST315Q08JA float, ST315Q09JA float, ST315Q10JA float, ST303Q01JA float, ST303Q02JA float, ST303Q03JA float, ST303Q04JA float, ST303Q05JA float, ST303Q06JA float, ST303Q07JA float, ST303Q08JA float, ST305Q01JA float, ST305Q02JA float, ST305Q03JA float, ST305Q04JA float, ST305Q05JA float, ST305Q06JA float, ST305Q07JA float, ST305Q08JA float, ST305Q09JA float, ST305Q10JA float, ST345Q01JA float, ST345Q02JA float, ST345Q03JA float, ST345Q04JA float, ST345Q05JA float, ST345Q06JA float, ST345Q07JA float, ST345Q08JA float, ST345Q09JA float, ST345Q10JA float, ST313Q01JA float, ST313Q02JA float, ST313Q03JA float, ST313Q04JA float, ST313Q05JA float, ST313Q06JA float, ST313Q07JA float, ST313Q08JA float, ST313Q09JA float, ST313Q10JA float, ST263Q02JA float, ST263Q04JA float, ST263Q06JA float, ST263Q08JA float, ST016Q01NA float, ST059Q01TA float, ST059Q02JA float, ST296Q01JA float, ST296Q02JA float, ST296Q03JA float, ST296Q04JA float, ST272Q01JA float, ST273Q01JA float, ST273Q02JA float, ST273Q03JA float, ST273Q04JA float, ST273Q05JA float, ST273Q06JA float, ST273Q07JA float, ST270Q01JA float, ST270Q02JA float, ST270Q03JA float, ST270Q04JA float, ST285Q01JA float, ST285Q02JA float, ST285Q03JA float, ST285Q04JA float, ST285Q05JA float, ST285Q06JA float, ST285Q07JA float, ST285Q08JA float, ST285Q09JA float, ST283Q01JA float, ST283Q02JA float, ST283Q03JA float, ST283Q04JA float, ST283Q05JA float, ST283Q06JA float, ST283Q07JA float, ST283Q08JA float, ST283Q09JA float, ST275Q01WA float, ST275Q02WA float, ST275Q03WA float, ST275Q04WA float, ST275Q05WA float, ST275Q06WA float, ST275Q07WA float, ST275Q08WA float, ST275Q09WA float, ST276Q01JA float, ST276Q02JA float, ST276Q03JA float, ST276Q04JA float, ST276Q05JA float, ST276Q06JA float, ST276Q07JA float, ST276Q08JA float, ST276Q09JA float, ST276Q10JA float, ST268Q01JA float, ST268Q02JA float, ST268Q03JA float, ST268Q04JA float, ST268Q05JA float, ST268Q06JA float, ST268Q07JA float, ST268Q08JA float, ST268Q09JA float, ST290Q01WA float, ST290Q02WA float, ST290Q03WA float, ST290Q04WA float, ST290Q05WA float, ST290Q06WA float, ST290Q07WA float, ST290Q08WA float, ST290Q09WA float, ST291Q01JA float, ST291Q02JA float, ST291Q03JA float, ST291Q04JA float, ST291Q05JA float, ST291Q06JA float, ST291Q07JA float, ST291Q08JA float, ST291Q09JA float, ST291Q10JA float, ST289Q01WA float, ST289Q02JA float, ST289Q03WA float, ST289Q04JA float, ST289Q05WA float, ST289Q06JA float, ST289Q07JA float, ST289Q08WA float, ST289Q09WA float, ST289Q10WA float, ST289Q11WA float, ST289Q14JA float, ST293Q01JA float, ST293Q02JA float, ST293Q03JA float, ST293Q04JA float, ST293Q05JA float, ST293Q06JA float, ST293Q07JA float, ST293Q08JA float, ST293Q09JA float, ST292Q01JA float, ST292Q02JA float, ST292Q03JA float, ST292Q04JA float, ST292Q05JA float, ST292Q06JA float, ST297Q01JA float, ST297Q03JA float, ST297Q05JA float, ST297Q06JA float, ST297Q07JA float, ST297Q09JA float, ST334Q01JA float, ST334Q02JA float, ST334Q03JA float, ST334Q04JA float, ST334Q05JA float, ST334Q06JA float, ST334Q07JA float, ST334Q08JA float, ST334Q09JA float, ST334Q10JA float, ST335Q01JA float, ST335Q02JA float, ST335Q03JA float, ST335Q05JA float, ST335Q06JA float, ST335Q07JA float, ST336Q01JA float, ST336Q03JA float, ST336Q04JA float, ST336Q05JA float, ST336Q06JA float, ST336Q07JA float, ST337Q01JA float, ST337Q02JA float, ST337Q03JA float, ST337Q04JA float, ST337Q05JA float, ST337Q06JA float, ST337Q07JA float, ST337Q08JA float, ST338Q01JA float, ST338Q02JA float, ST338Q03JA float, ST338Q04JA float, ST338Q05JA float, ST338Q06JA float, ST338Q07JA float, ST338Q08JA float, ST339Q04JA float, ST339Q06JA float, ST340Q01JA float, ST340Q02JA float, ST340Q03JA float, ST340Q04JA float, ST340Q05JA float, ST340Q06JA float, ST340Q07JA float, ST340Q08JA float, ST340Q09JA float, ST340Q10JA float, ST341Q01JA float, ST341Q02JA float, ST341Q03JA float, ST341Q04JA float, ST341Q05JA float, ST342Q01JA float, ST342Q02JA float, ST342Q03JA float, ST342Q04JA float, ST342Q06JA float, ST342Q07JA float, ST342Q08JA float, ST300Q01JA float, ST300Q02JA float, ST300Q03JA float, ST300Q04JA float, ST300Q05JA float, ST300Q06JA float, ST300Q07JA float, ST300Q08JA float, ST300Q09JA float, ST300Q10JA float, ST327Q01JA float, ST327Q02JA float, ST327Q03JA float, ST327Q04JA float, ST327Q05JA float, ST327Q06JA float, ST327Q07JA float, ST327Q08JA float, ST330Q01WA float, ST330Q02WA float, ST330Q03WA float, ST330Q04WA float, ST330Q05WA float, ST330Q06WA float, ST330Q07WA float, ST330Q08WA float, ST330Q09WA float, ST330Q11WA float, ST330D10WA varchar(20), ST324Q02JA float, ST324Q04JA float, ST324Q05JA float, ST324Q07JA float, ST324Q10JA float, ST324Q11JA float, ST324Q12JA float, ST324Q13JA float, ST324Q14JA float, ST347Q01JA float, ST347Q02JA float, ST348Q01JA float, ST348Q02JA float, ST348Q03JA float, ST348Q04JA float, ST348Q05JA float, ST348Q06JA float, ST348Q07JA float, ST348Q08JA float, ST349Q01JA float, ST350Q01JA float, ST351Q01JA float, ST351Q02JA float, ST351Q03JA float, ST351Q04JA float, ST351Q05JA float, ST351Q06JA float, ST351Q07JA float, ST351Q08JA float, ST352Q01JA float, ST352Q02JA float, ST352Q03JA float, ST352Q04JA float, ST352Q05JA float, ST352Q06JA float, ST352Q07JA float, ST352Q08JA float, ST353Q01JA float, ST353Q02JA float, ST353Q03JA float, ST353Q04JA float, ST353Q05JA float, ST353Q06JA float, ST353Q07JA float, ST353Q08JA float, ST354Q01JA float, ST354Q02JA float, ST354Q03JA float, ST354Q04JA float, ST354Q05JA float, ST354Q06JA float, ST354Q07JA float, ST354Q08JA float, ST354Q09JA float, ST354Q10JA float, ST355Q01JA float, ST355Q02JA float, ST355Q03JA float, ST355Q04JA float, ST355Q05JA float, ST355Q06JA float, ST355Q07JA float, ST355Q08JA float, ST356Q01JA float, ST331Q01JA float, ST331Q02JA float, ST331Q03JA float, FL150Q01TA float, FL150Q02TA float, FL150Q03TA float, FL164Q01HA float, FL164Q02HA float, FL164Q03HA float, FL164Q04HA float, FL164Q05HA float, FL164Q06HA float, FL164Q07HA float, FL164Q08HA float, FL164Q09HA float, FL164Q10HA float, FL164Q11HA float, FL164Q12HA float, FL164Q13HA float, FL164Q14HA float, FL164Q15HA float, FL164Q16HA float, FL166Q01HA float, FL166Q02HA float, FL166Q03HA float, FL166Q05HA float, FL166Q06HA float, FL166Q07HA float, FL174Q01JA float, FL174Q02JA float, FL174Q03JA float, FL174Q04JA float, FL174Q05JA float, FL174Q06JA float, FL174Q07JA float, FL167Q01HA float, FL167Q02HA float, FL167Q06JA float, FL167Q03HA float, FL167Q04HA float, FL167Q05HA float, FL167Q07JA float, FL170Q01JA float, FL170Q02JA float, FL170Q03JA float, FL170Q04JA float, FL170Q05JA float, FL170Q06JA float, FL170Q07JA float, FL159Q01HA float, FL159Q02HA float, FL159Q03HA float, FL159Q04HA float, FL160Q01HA float, FL160Q02HA float, FL160Q03HA float, FL160Q04HA float, FL161Q01HA float, FL161Q02HA float, FL161Q03HA float, FL162Q01HA float, FL162Q02HA float, FL162Q03HA float, FL162Q04HA float, FL162Q05HA float, FL162Q06HA float, FL163Q01HA float, FL163Q02HA float, FL163Q03HA float, FL163Q04HA float, FL163Q05HA float, FL171Q01JA float, FL171Q02JA float, FL171Q03JA float, FL171Q04JA float, FL171Q05JA float, FL171Q07JA float, FL171Q08JA float, FL171Q09JA float, FL171Q10JA float, FL171Q11JA float, FL171Q12JA float, FL169Q01HA float, FL169Q05JA float, FL169Q02HA float, FL169Q06JA float, FL169Q07JA float, FL169Q03HA float, FL169Q04HA float, FL169Q08JA float, FL169Q10JA float, FL169Q11JA float, FL172Q01JA float, FL172Q03JA float, FL172Q05JA float, FL172Q06JA float, IC170Q01JA float, IC170Q02JA float, IC170Q03JA float, IC170Q04JA float, IC170Q05JA float, IC170Q06JA float, IC170Q07JA float, IC171Q01JA float, IC171Q02JA float, IC171Q03JA float, IC171Q04JA float, IC171Q05JA float, IC171Q06JA float, IC172Q01JA float, IC172Q02JA float, IC172Q03JA float, IC172Q04JA float, IC172Q05JA float, IC172Q06JA float, IC172Q07JA float, IC172Q08JA float, IC172Q09JA float, IC173Q01JA float, IC173Q02JA float, IC173Q03JA float, IC173Q04JA float, IC174Q01JA float, IC174Q02JA float, IC174Q03JA float, IC174Q04JA float, IC174Q05JA float, IC174Q06JA float, IC174Q07JA float, IC174Q08JA float, IC174Q09JA float, IC174Q10JA float, IC175Q01JA float, IC175Q02JA float, IC175Q03JA float, IC175Q05JA float, IC176Q01JA float, IC176Q02JA float, IC176Q03JA float, IC176Q04JA float, IC176Q05JA float, IC176Q06JA float, IC176Q07JA float, IC176Q08JA float, IC184Q01JA float, IC184Q02JA float, IC184Q03JA float, IC184Q04JA float, IC177Q01JA float, IC177Q02JA float, IC177Q03JA float, IC177Q04JA float, IC177Q05JA float, IC177Q06JA float, IC177Q07JA float, IC178Q01JA float, IC178Q02JA float, IC178Q03JA float, IC178Q04JA float, IC178Q05JA float, IC178Q06JA float, IC178Q07JA float, IC179Q01JA float, IC179Q02JA float, IC179Q03JA float, IC179Q04JA float, IC179Q05JA float, IC179Q06JA float, IC180Q01JA float, IC180Q02JA float, IC180Q03JA float, IC180Q04JA float, IC180Q05JA float, IC180Q06JA float, IC180Q07JA float, IC180Q08JA float, IC181Q01JA float, IC181Q02JA float, IC181Q03JA float, IC181Q04JA float, IC182Q01JA float, IC182Q02JA float, IC182Q03JA float, IC183Q01JA float, IC183Q02JA float, IC183Q03JA float, IC183Q04JA float, IC183Q05JA float, IC183Q07JA float, IC183Q08JA float, IC183Q09JA float, IC183Q10JA float, IC183Q12JA float, IC183Q13JA float, IC183Q14JA float, IC183Q15JA float, IC183Q16JA float, WB150Q01HA float, WB151Q01HA float, WB152Q01HA float, WB153Q01HA float, WB153Q02HA float, WB153Q03HA float, WB153Q04HA float, WB153Q05HA float, WB154Q01HA float, WB154Q02HA float, WB154Q03HA float, WB154Q04HA float, WB154Q05HA float, WB154Q06HA float, WB154Q07HA float, WB154Q08HA float, WB154Q09HA float, WB155Q01HA float, WB155Q02HA float, WB155Q03HA float, WB155Q04HA float, WB155Q05HA float, WB155Q06HA float, WB155Q07HA float, WB155Q08HA float, WB155Q09HA float, WB155Q10HA float, WB156Q01HA float, WB158Q01HA float, WB160Q01HA float, WB161Q01HA float, WB162Q01HA float, WB162Q02HA float, WB162Q03HA float, WB162Q04HA float, WB162Q05HA float, WB162Q06HA float, WB162Q07HA float, WB162Q08HA float, WB162Q09HA float, WB163Q01HA float, WB163Q02HA float, WB163Q03HA float, WB163Q04HA float, WB163Q05HA float, WB163Q06HA float, WB163Q07HA float, WB163Q08HA float, WB164Q01HA float, WB165Q01HA float, WB166Q01HA float, WB166Q02HA float, WB166Q03HA float, WB166Q04HA float, WB167Q01HA float, WB168Q01HA float, WB168Q02HA float, WB168Q03HA float, WB168Q04HA float, WB171Q01HA float, WB171Q02HA float, WB171Q03HA float, WB171Q04HA float, WB172Q01HA float, WB173Q01HA float, WB173Q02HA float, WB173Q03HA float, WB173Q04HA float, WB176Q01HA float, WB177Q01HA float, WB177Q02HA float, WB177Q03HA float, WB177Q04HA float, WB032Q01NA float, WB032Q02NA float, WB031Q01NA float, WB178Q01HA float, WB178Q02HA float, WB178Q03HA float, WB178Q04HA float, WB178Q05HA float, WB178Q06HA float, WB178Q07HA float, PA001Q01TA float, PA001Q02TA float, PA001Q03TA float, PA003Q01TA float, PA003Q02TA float, PA003Q03TA float, PA003Q05IA float, PA003Q18WA float, PA003Q19WA float, PA003Q20WA float, PA003Q11JA float, PA003Q12JA float, PA003Q13JA float, PA003Q14JA float, PA003Q15JA float, PA003Q16JA float, PA003Q17JA float, PA196Q01WA float, PA196Q02WA float, PA196Q03WA float, PA196Q04WA float, PA197Q01WA float, PA197Q02WA float, PA197Q03WA float, PA197Q04WA float, PA197Q05WA float, PA008Q01TA float, PA008Q02TA float, PA008Q03TA float, PA008Q04TA float, PA008Q05TA float, PA008Q06NA float, PA008Q07NA float, PA008Q08NA float, PA008Q09NA float, PA008Q10NA float, PA009Q01NA float, PA009Q02NA float, PA009Q03NA float, PA009Q04NA float, PA009Q05NA float, PA009Q06NA float, PA009Q07NA float, PA009Q08NA float, PA009Q09NA float, PA009Q10NA float, PA009Q11NA float, PA007Q01TA float, PA007Q02TA float, PA007Q03TA float, PA007Q04TA float, PA007Q05TA float, PA007Q06TA float, PA007Q07TA float, PA007Q09NA float, PA007Q11NA float, PA007Q12NA float, PA007Q13NA float, PA007Q14NA float, PA007Q15NA float, PA005Q01TA float, PA006Q01TA float, PA006Q02TA float, PA006Q03TA float, PA006Q04TA float, PA006Q05TA float, PA006Q06TA float, PA006Q07TA float, PA006Q08TA float, PA006Q09TA float, PA006Q10TA float, PA006Q11TA float, PA006Q12HA float, PA006Q13HA float, PA006Q14HA float, PA166Q01HA float, PA167Q02HA float, PA167Q03HA float, PA167Q04HA float, PA167Q05HA float, PA183Q01JA float, PA183Q02JA float, PA183Q03JA float, PA183Q04JA float, PA183Q05JA float, PA183Q06JA float, PA183Q07JA float, PA183Q08JA float, PA018Q01NA float, PA018Q02NA float, PA018Q03NA float, PA177Q01HA float, PA177Q02HA float, PA177Q03HA float, PA177Q04HA float, PA177Q05HA float, PA177Q06HA float, PA177Q07HA float, PA177Q08HA float, PA180Q01HA float, PA182Q01HA float, PA175Q01HA float, PA175Q02HA float, PA175Q03JA float, PA175Q04JA float, PA185Q01JA float, PA185Q02JA float, PA185Q03JA float, PA185Q04JA float, PA185Q05JA float, PA185Q07JA float, PA185Q08JA float, PA185Q09JA float, PA185Q10JA float, PA186Q01JA float, PA186Q02JA float, PA186Q03JA float, PA186Q04JA float, PA186Q05JA float, PA186Q06JA float, PA186Q07JA float, PA186Q08JA float, PA187Q04JA float, PA187Q06JA float, PA188Q01JA float, PA188Q02JA float, PA188Q03JA float, PA188Q04JA float, PA188Q05JA float, PA188Q06JA float, PA188Q08JA float, PA188Q09JA float, PA188Q10JA float, PA189Q01JA float, PA189Q02JA float, PA189Q03JA float, PA189Q04JA float, PA189Q05JA float, PA189Q06JA float, PA189Q09JA float, PA189Q10JA float, PA194Q01JA float, PA195Q01JA float, PA041Q01TA float, PA042Q01TA float, EFFORT1 float, EFFORT2 float, OCOD1 varchar(20), OCOD2 varchar(20), OCOD3 varchar(20), PROGN varchar(20), AGE float, GRADE float, ISCEDP float, IMMIG float, COBN_S varchar(20), COBN_M varchar(20), COBN_F varchar(20), LANGN float, REPEAT float, MISSSC float, SKIPPING float, TARDYSD float, EXERPRAC float, STUDYHMW float, WORKPAY float, WORKHOME float, EXPECEDU float, MATHPREF float, MATHEASE float, MATHMOT float, DURECEC float, BSMJ float, SISCO float, RELATST float, BELONG float, BULLIED float, FEELSAFE float, SCHRISK float, PERSEVAGR float, CURIOAGR float, COOPAGR float, EMPATAGR float, ASSERAGR float, STRESAGR float, EMOCOAGR float, GROSAGR float, INFOSEEK float, FAMSUP float, DISCLIM float, TEACHSUP float, COGACRCO float, COGACMCO float, EXPOFA float, EXPO21ST float, MATHEFF float, MATHEF21 float, FAMCON float, ANXMAT float, MATHPERS float, CREATEFF float, CREATSCH float, CREATFAM float, CREATAS float, CREATOOS float, CREATOP float, OPENART float, IMAGINE float, SCHSUST float, LEARRES float, PROBSELF float, FAMSUPSL float, FEELLAH float, SDLEFF float, MISCED float, FISCED float, HISCED float, PAREDINT float, BMMJ1 float, BFMJ2 float, HISEI float, ICTRES float, HOMEPOS float, ESCS float, FCFMLRTY float, FLSCHOOL float, FLMULTSB float, FLFAMILY float, ACCESSFP float, FLCONFIN float, FLCONICT float, ACCESSFA float, ATTCONFM float, FRINFLFM float, ICTSCH float, ICTAVSCH float, ICTHOME float, ICTAVHOM float, ICTQUAL float, ICTSUBJ float, ICTENQ float, ICTFEED float, ICTOUT float, ICTWKDY float, ICTWKEND float, ICTREG float, ICTINFO float, ICTDISTR float, ICTEFFIC float, STUBMI float, BODYIMA float, SOCONPA float, LIFESAT float, PSYCHSYM float, SOCCON float, EXPWB float, CURSUPP float, PQMIMP float, PQMCAR float, PARINVOL float, PQSCHOOL float, PASCHPOL float, ATTIMMP float, PAREXPT float, CREATHME float, CREATACT float, CREATOPN float, CREATOR float, W_FSTUWT float, W_FSTURWT1 float, W_FSTURWT2 float, W_FSTURWT3 float, W_FSTURWT4 float, W_FSTURWT5 float, W_FSTURWT6 float, W_FSTURWT7 float, W_FSTURWT8 float, W_FSTURWT9 float, W_FSTURWT10 float, W_FSTURWT11 float, W_FSTURWT12 float, W_FSTURWT13 float, W_FSTURWT14 float, W_FSTURWT15 float, W_FSTURWT16 float, W_FSTURWT17 float, W_FSTURWT18 float, W_FSTURWT19 float, W_FSTURWT20 float, W_FSTURWT21 float, W_FSTURWT22 float, W_FSTURWT23 float, W_FSTURWT24 float, W_FSTURWT25 float, W_FSTURWT26 float, W_FSTURWT27 float, W_FSTURWT28 float, W_FSTURWT29 float, W_FSTURWT30 float, W_FSTURWT31 float, W_FSTURWT32 float, W_FSTURWT33 float, W_FSTURWT34 float, W_FSTURWT35 float, W_FSTURWT36 float, W_FSTURWT37 float, W_FSTURWT38 float, W_FSTURWT39 float, W_FSTURWT40 float, W_FSTURWT41 float, W_FSTURWT42 float, W_FSTURWT43 float, W_

In [28]:

pisa2022_df['OECD'].replace({0: 'NON-OECD', 1: 'OECD'}, inplace=True)
pisa2022_df

,CNT,CNTRYID,CNTSCHID,CNTSTUID,CYC,NatCen,STRATUM,SUBNATIO,REGION,OECD,...,PV4MPRE,PV5MPRE,PV6MPRE,PV7MPRE,PV8MPRE,PV9MPRE,PV10MPRE,SENWT,VER_DAT,i
0,ALB,8.0,800282.0,800001.0,08MS,000800,ALB03,0080000,800.0,NON-OECD,...,203.029,219.817,331.017,223.752,305.671,230.156,289.436,0.55561,03MAY23:10:11:25,218.0
1,ALB,8.0,800115.0,800002.0,08MS,000800,ALB03,0080000,800.0,NON-OECD,...,321.405,320.452,284.836,364.565,304.044,347.626,352.269,0.76431,03MAY23:10:11:25,218.0
2,ALB,8.0,800242.0,800003.0,08MS,000800,ALB01,0080000,800.0,NON-OECD,...,376.019,285.901,289.896,338.469,316.296,324.361,343.351,1.37877,03MAY23:10:11:25,218.0
3,ALB,8.0,800245.0,800005.0,08MS,000800,ALB08,0080000,800.0,NON-OECD,...,303.422,327.793,165.575,246.156,238.322,275.860,227.466,1.49361,03MAY23:10:11:26,218.0
4,ALB,8.0,800285.0,800006.0,08MS,000800,ALB03,0080000,800.0,NON-OECD,...,514.739,539.850,461.793,514.465,510.462,490.537,503.793,0.65249,03MAY23:10:11:26,218.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
613739,UZB,860.0,86000120.0,86007488.0,08MS,086000,UZB26,8600000,86000.0,NON-OECD,...,306.551,271.135,386.969,376.271,368.287,395.329,278.263,0.71987,02MAY23:13:18:15,218.0
613740,UZB,860.0,86000140.0,86007489.0,08MS,086000,UZB04,8600000,86000.0,NON-OECD,...,335.952,232.583,179.328,233.470,203.001,254.340,233.187,0.65541,02MAY23:13:18:13,218.0
613741,UZB,860.0,86000024.0,86007490.0,08MS,086000,UZB10,8600000,86000.0,NON-OECD,...,451.614,432.586,387.329,456.236,424.790,408.986,460.542,0.67910,02MAY23:13:18:13,218.0
613742,UZB,860.0,86000174.0,86007491.0,08MS,086000,UZB16,8600000,86000.0,NON-OECD,...,272.346,317.838,248.165,405.860,364.173,346.663,341.668,0.68618,02MAY23:13:18:14,218.0
613743,UZB,860.0,86000123.0,86007492.0,08MS,086000,UZB10,8600000,86000.0,NON-OECD,...,416.631,337.422,370.817,395.176,412.317,390.490,439.211,0.67910,02MAY23:13:18:13,218.0

In [29]:
# Calculate NaN percentage for each column
nan_percentage = (pisa2022_df.isna().sum() / len(pisa2022_df)) * 100

# Calculate NaN percentage for each row
nan_percentage_rows = (pisa2022_df.isna().sum(axis=1) / len(pisa2022_df.columns)) * 100

In [30]:
# Delete columns with NaN percentage greater than 60%
columns_to_delete = nan_percentage[nan_percentage > 75].index
pisa2022_df.drop(columns=columns_to_delete, inplace=True)

"""# Delete rows with NaN percentage greater than 60%
rows_to_delete = nan_percentage_rows[nan_percentage_rows > 60].index
pisa2022_school_df.drop(index=rows_to_delete, inplace=True)"""

'# Delete rows with NaN percentage greater than 60%\nrows_to_delete = nan_percentage_rows[nan_percentage_rows > 60].index\npisa2022_school_df.drop(index=rows_to_delete, inplace=True)'

In [31]:
pisa2022_df = pisa2022_df.fillna(value=0)

2022 PISA Score Dataset

In [ ]:
###pisa2022_avr_scores_df  = pd.read_csv(r"C:\1stApril\Work\4rd_Year\4rd2\CSS400_Project_Development\CN1-2023\pisa2022_analysis\StreamlitDev\data_file\data\Average_score.csv", encoding = "ISO-8859-1")
###pisa2022_avr_scores_df

2022 PISA Math Scores

In [ ]:
###pisa2022_math_scores_df = pd.read_csv(r"C:\1stApril\Work\4rd_Year\4rd2\CSS400 Project Development\CN1-2023\PisaTest2022-analysis\csv_file_data\data\math_score.csv",encoding = "ISO-8859-1")
###pisa2022_math_scores_df

2022 PISA Science Scores

In [ ]:
#pisa2022_sci_scores_df = pd.read_csv(r"C:\1stApril\Work\4rd_Year\4rd2\CSS400 Project Development\CN1-2023\PisaTest2022-analysis\csv_file_data\data\Science_score.csv", encoding = "ISO-8859-1")
###pisa2022_sci_scores_df

2022 PISA Reading Scores

In [ ]:
#pisa2022_read_scores_df = pd.read_csv(r"C:\1stApril\Work\4rd_Year\4rd2\CSS400 Project Development\CN1-2023\PisaTest2022-analysis\csv_file_data\data\Reading_score.csv", encoding = "ISO-8859-1")
###pisa2022_read_scores_df

In [ ]:
#pisa2022_sci_scores_df.info()

ISO alpha-3 code list

In [32]:
if os.path.exists(r"C:\1stApril\Work\4rd_Year\4rd2\CSS400_Project_Development\CN1-2023\pisa2022_analysis\StreamlitDev\data_file\data\country_codes.csv"):
    os.remove(r"C:\1stApril\Work\4rd_Year\4rd2\CSS400_Project_Development\CN1-2023\pisa2022_analysis\StreamlitDev\data_file\data\country_codes.csv")

file_input = open(r"C:\1stApril\Work\4rd_Year\4rd2\CSS400_Project_Development\CN1-2023\pisa2022_analysis\StreamlitDev\data_file\raw\country_codes.txt", "r")
file_output = open(r"C:\1stApril\Work\4rd_Year\4rd2\CSS400_Project_Development\CN1-2023\pisa2022_analysis\StreamlitDev\data_file\data\country_codes.csv", "w")

# Add a header
file_output.write("Code,Country/Region\n")

# Replace the space separator with a comma
for line in file_input:
    new_line = line[:3] + ',' + line[4:]
    file_output.write(new_line)

file_input.close()
file_output.close()

In [33]:
country_codes_file = open(r"C:\1stApril\Work\4rd_Year\4rd2\CSS400_Project_Development\CN1-2023\pisa2022_analysis\StreamlitDev\data_file\data\country_codes.csv", "r")

for line in country_codes_file:
    if (line.count(',') > 1):
        print(line)

country_codes_file.close()

BOL,Bolivia, Plurinational State of

COD,Congo, the Democratic Republic of the

FSM,Micronesia, Federated States of

IRN,Iran, Islamic Republic of

KOR,Korea, Republic of

MDA,Moldova, Republic of

MKD,Macedonia, the former Yugoslav Republic of

PRK,Korea, Democratic People's Republic of

PSE,Palestinian Territory, Occupied

SHN,Saint Helena, Ascension and Tristan da Cunha

TAP,Taiwan, Province of China

TZA,Tanzania, United Republic of

VEN,Venezuela, Bolivarian Republic of

VGB,Virgin Islands, British

VIR,Virgin Islands, U.S.

In [34]:
# Open the file in read mode
country_codes_file = open(r"C:\1stApril\Work\4rd_Year\4rd2\CSS400_Project_Development\CN1-2023\pisa2022_analysis\StreamlitDev\data_file\data\country_codes.csv", "r")

# Replace all instances of ", " with "-"
country_codes_data = country_codes_file.read()
country_codes_data = country_codes_data.replace(", ", " - ")

country_codes_file.close()

# Open the file again in write mode
country_codes_file = open(r"C:\1stApril\Work\4rd_Year\4rd2\CSS400_Project_Development\CN1-2023\pisa2022_analysis\StreamlitDev\data_file\data\country_codes.csv", "w")
country_codes_file.write(country_codes_data)
country_codes_file.close()

CONSTRUCTED ISO 3166-1 ALPHA-3 CODE LIST

In [35]:
country_codes_df = pd.read_csv(r"C:\1stApril\Work\4rd_Year\4rd2\CSS400_Project_Development\CN1-2023\pisa2022_analysis\StreamlitDev\data_file\data\country_codes.csv")

In [36]:
country_codes_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 246 entries, 0 to 245
Data columns (total 2 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Code            246 non-null    object
 1   Country/Region  246 non-null    object
dtypes: object(2)
memory usage: 4.0+ KB

DATA PREPROCESSING

Merging the 2022 PISA School Dataset and ISO  alpha-3 Code List

In [ ]:
###pisa2022_df = pisa2022_school_df.merge(country_codes_df, left_on = "CNT", right_on = "Code", how = 'left')
###pisa2022_df

Check for null values in 'Country/Region'

In [37]:
pisa2022_df[pisa2022_df['Country/Region'].isnull()]['CNT'].unique()

KeyError: 'Country/Region'

In [38]:
addl_codes = {"QAZ": "Azerbaijan",
              "TAP": "Taiwan",
              "KSV": "Kosovo",
              "QUR": "Ukraine"}

In [39]:
for code, country in addl_codes.items():
    pisa2022_df.loc[pisa2022_df['CNT'] == code, 'Country/Region'] = country
    
pisa2022_df

C:\Users\1stApril\AppData\Local\Temp\ipykernel_19168\2071018841.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pisa2022_df.loc[pisa2022_df['CNT'] == code, 'Country/Region'] = country

,CNT,CNTRYID,CNTSCHID,CNTSTUID,CYC,NatCen,STRATUM,SUBNATIO,REGION,OECD,...,PV5MPRE,PV6MPRE,PV7MPRE,PV8MPRE,PV9MPRE,PV10MPRE,SENWT,VER_DAT,i,Country/Region
0,ALB,8.0,800282.0,800001.0,08MS,000800,ALB03,0080000,800.0,NON-OECD,...,219.817,331.017,223.752,305.671,230.156,289.436,0.55561,03MAY23:10:11:25,218.0,nan
1,ALB,8.0,800115.0,800002.0,08MS,000800,ALB03,0080000,800.0,NON-OECD,...,320.452,284.836,364.565,304.044,347.626,352.269,0.76431,03MAY23:10:11:25,218.0,nan
2,ALB,8.0,800242.0,800003.0,08MS,000800,ALB01,0080000,800.0,NON-OECD,...,285.901,289.896,338.469,316.296,324.361,343.351,1.37877,03MAY23:10:11:25,218.0,nan
3,ALB,8.0,800245.0,800005.0,08MS,000800,ALB08,0080000,800.0,NON-OECD,...,327.793,165.575,246.156,238.322,275.860,227.466,1.49361,03MAY23:10:11:26,218.0,nan
4,ALB,8.0,800285.0,800006.0,08MS,000800,ALB03,0080000,800.0,NON-OECD,...,539.850,461.793,514.465,510.462,490.537,503.793,0.65249,03MAY23:10:11:26,218.0,nan
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
613739,UZB,860.0,86000120.0,86007488.0,08MS,086000,UZB26,8600000,86000.0,NON-OECD,...,271.135,386.969,376.271,368.287,395.329,278.263,0.71987,02MAY23:13:18:15,218.0,nan
613740,UZB,860.0,86000140.0,86007489.0,08MS,086000,UZB04,8600000,86000.0,NON-OECD,...,232.583,179.328,233.470,203.001,254.340,233.187,0.65541,02MAY23:13:18:13,218.0,nan
613741,UZB,860.0,86000024.0,86007490.0,08MS,086000,UZB10,8600000,86000.0,NON-OECD,...,432.586,387.329,456.236,424.790,408.986,460.542,0.67910,02MAY23:13:18:13,218.0,nan
613742,UZB,860.0,86000174.0,86007491.0,08MS,086000,UZB16,8600000,86000.0,NON-OECD,...,317.838,248.165,405.860,364.173,346.663,341.668,0.68618,02MAY23:13:18:14,218.0,nan
613743,UZB,860.0,86000123.0,86007492.0,08MS,086000,UZB10,8600000,86000.0,NON-OECD,...,337.422,370.817,395.176,412.317,390.490,439.211,0.67910,02MAY23:13:18:13,218.0,nan

In [40]:
pisa2022_df['Country/Region'].isnull().values.any()

False

2. Merging the 2022 PISA School Dataset, ISO  alpha-3 Code List, and 2022 PISA Scores Dataset

In [ ]:
#pisa_school_only = set(pisa2022_school_df['Country/Region']) - set(pisa2022_avr_scores_df['Country/Region'])
#pisa_school_only

In [42]:
pisa_school_only_tokens = {}
excluded = ['of', 'the', '-', 'former', 'Federation', 'Republic', 'Occupied', 'Yugoslav' ]

for region in pisa2022_df:
    # Remove punctuation marks
    region_clean = region.replace('(', '')
    region_clean = region_clean.replace(')', '')
    region_clean = region_clean.replace(',', '')
    region_clean = region_clean.replace(',', '')
    
    pisa_school_only_tokens[region] = set()
    
    # Tokenize the country/region name into constituent words
    for token in region_clean.split():
        if token not in excluded:
            pisa_school_only_tokens[region].add(token)
            
pisa_school_only_tokens

{'CNT': {'CNT'},
 'CNTRYID': {'CNTRYID'},
 'CNTSCHID': {'CNTSCHID'},
 'CNTSTUID': {'CNTSTUID'},
 'CYC': {'CYC'},
 'NatCen': {'NatCen'},
 'STRATUM': {'STRATUM'},
 'SUBNATIO': {'SUBNATIO'},
 'REGION': {'REGION'},
 'OECD': {'OECD'},
 'ADMINMODE': {'ADMINMODE'},
 'LANGTEST_QQQ': {'LANGTEST_QQQ'},
 'LANGTEST_COG': {'LANGTEST_COG'},
 'Option_ICTQ': {'Option_ICTQ'},
 'Option_WBQ': {'Option_WBQ'},
 'Option_PQ': {'Option_PQ'},
 'Option_TQ': {'Option_TQ'},
 'Option_UH': {'Option_UH'},
 'BOOKID': {'BOOKID'},
 'ST001D01T': {'ST001D01T'},
 'ST003D02T': {'ST003D02T'},
 'ST003D03T': {'ST003D03T'},
 'ST004D01T': {'ST004D01T'},
 'ST250Q01JA': {'ST250Q01JA'},
 'ST250Q02JA': {'ST250Q02JA'},
 'ST250Q03JA': {'ST250Q03JA'},
 'ST250Q04JA': {'ST250Q04JA'},
 'ST250Q05JA': {'ST250Q05JA'},
 'ST250D06JA': {'ST250D06JA'},
 'ST250D07JA': {'ST250D07JA'},
 'ST251Q01JA': {'ST251Q01JA'},
 'ST251Q02JA': {'ST251Q02JA'},
 'ST251Q03JA': {'ST251Q03JA'},
 'ST251Q04JA': {'ST251Q04JA'},
 'ST251Q06JA': {'ST251Q06JA'},
 'ST251Q07JA': {'ST251Q07JA'},
 'ST251D08JA': {'ST251D08JA'},
 'ST251D09JA': {'ST251D09JA'},
 'ST253Q01JA': {'ST253Q01JA'},
 'ST254Q01JA': {'ST254Q01JA'},
 'ST254Q02JA': {'ST254Q02JA'},
 'ST254Q03JA': {'ST254Q03JA'},
 'ST254Q04JA': {'ST254Q04JA'},
 'ST254Q05JA': {'ST254Q05JA'},
 'ST254Q06JA': {'ST254Q06JA'},
 'ST255Q01JA': {'ST255Q01JA'},
 'ST256Q01JA': {'ST256Q01JA'},
 'ST256Q02JA': {'ST256Q02JA'},
 'ST256Q03JA': {'ST256Q03JA'},
 'ST256Q06JA': {'ST256Q06JA'},
 'ST256Q07JA': {'ST256Q07JA'},
 'ST256Q08JA': {'ST256Q08JA'},
 'ST256Q09JA': {'ST256Q09JA'},
 'ST256Q10JA': {'ST256Q10JA'},
 'ST230Q01JA': {'ST230Q01JA'},
 'ST005Q01JA': {'ST005Q01JA'},
 'ST006Q01JA': {'ST006Q01JA'},
 'ST006Q02JA': {'ST006Q02JA'},
 'ST006Q03JA': {'ST006Q03JA'},
 'ST006Q04JA': {'ST006Q04JA'},
 'ST006Q05JA': {'ST006Q05JA'},
 'ST007Q01JA': {'ST007Q01JA'},
 'ST008Q01JA': {'ST008Q01JA'},
 'ST008Q02JA': {'ST008Q02JA'},
 'ST008Q03JA': {'ST008Q03JA'},
 'ST008Q04JA': {'ST008Q04JA'},
 'ST008Q05JA': {'ST008Q05JA'},
 'ST258Q01JA': {'ST258Q01JA'},
 'ST259Q01JA': {'ST259Q01JA'},
 'ST259Q02JA': {'ST259Q02JA'},
 'ST019AQ01T': {'ST019AQ01T'},
 'ST019BQ01T': {'ST019BQ01T'},
 'ST019CQ01T': {'ST019CQ01T'},
 'ST022Q01TA': {'ST022Q01TA'},
 'ST226Q01JA': {'ST226Q01JA'},
 'ST125Q01NA': {'ST125Q01NA'},
 'ST126Q01TA': {'ST126Q01TA'},
 'ST127Q01TA': {'ST127Q01TA'},
 'ST127Q02TA': {'ST127Q02TA'},
 'ST127Q03TA': {'ST127Q03TA'},
 'ST260Q01JA': {'ST260Q01JA'},
 'ST260Q02JA': {'ST260Q02JA'},
 'ST260Q03JA': {'ST260Q03JA'},
 'ST062Q01TA': {'ST062Q01TA'},
 'ST062Q02TA': {'ST062Q02TA'},
 'ST062Q03TA': {'ST062Q03TA'},
 'ST267Q01JA': {'ST267Q01JA'},
 'ST267Q02JA': {'ST267Q02JA'},
 'ST267Q03JA': {'ST267Q03JA'},
 'ST267Q04JA': {'ST267Q04JA'},
 'ST267Q05JA': {'ST267Q05JA'},
 'ST267Q06JA': {'ST267Q06JA'},
 'ST267Q07JA': {'ST267Q07JA'},
 'ST267Q08JA': {'ST267Q08JA'},
 'ST034Q01TA': {'ST034Q01TA'},
 'ST034Q02TA': {'ST034Q02TA'},
 'ST034Q03TA': {'ST034Q03TA'},
 'ST034Q04TA': {'ST034Q04TA'},
 'ST034Q05TA': {'ST034Q05TA'},
 'ST034Q06TA': {'ST034Q06TA'},
 'ST038Q03NA': {'ST038Q03NA'},
 'ST038Q04NA': {'ST038Q04NA'},
 'ST038Q05NA': {'ST038Q05NA'},
 'ST038Q06NA': {'ST038Q06NA'},
 'ST038Q07NA': {'ST038Q07NA'},
 'ST038Q08NA': {'ST038Q08NA'},
 'ST038Q09JA': {'ST038Q09JA'},
 'ST038Q10JA': {'ST038Q10JA'},
 'ST038Q11JA': {'ST038Q11JA'},
 'ST265Q01JA': {'ST265Q01JA'},
 'ST265Q02JA': {'ST265Q02JA'},
 'ST265Q03JA': {'ST265Q03JA'},
 'ST265Q04JA': {'ST265Q04JA'},
 'ST266Q01JA': {'ST266Q01JA'},
 'ST266Q02JA': {'ST266Q02JA'},
 'ST266Q03JA': {'ST266Q03JA'},
 'ST266Q04JA': {'ST266Q04JA'},
 'ST266Q05JA': {'ST266Q05JA'},
 'ST294Q01JA': {'ST294Q01JA'},
 'ST294Q02JA': {'ST294Q02JA'},
 'ST294Q03JA': {'ST294Q03JA'},
 'ST294Q04JA': {'ST294Q04JA'},
 'ST294Q05JA': {'ST294Q05JA'},
 'ST295Q01JA': {'ST295Q01JA'},
 'ST295Q02JA': {'ST295Q02JA'},
 'ST295Q03JA': {'ST295Q03JA'},
 'ST295Q04JA': {'ST295Q04JA'},
 'ST295Q05JA': {'ST295Q05JA'},
 'ST326Q01JA': {'ST326Q01JA'},
 'ST326Q02JA': {'ST326Q02JA'},
 'ST326Q03JA': {'ST326Q03JA'},
 'ST326Q04JA': {'ST326Q04JA'},
 'ST326Q05JA': {'ST326Q05JA'},
 'ST326Q06JA': {'ST326Q06JA'},
 'ST322Q01JA': {'ST322Q01JA'},
 'ST322Q02JA': {'ST322Q02JA'},
 'ST322Q03JA': {'ST322Q03JA'},
 'ST322Q04JA': {'ST322Q04JA'},
 'ST322Q06JA': {'ST322Q06JA'},
 'ST322Q07JA': {'ST322Q07JA'},
 'ST307Q01JA': {'ST307Q01JA'},
 'ST307Q02JA': {'ST307Q02JA'},
 'ST307Q03JA': {'ST307Q03JA'},
 'ST307Q04JA': {'ST307Q04JA'},
 'ST307Q05JA': {'ST307Q05JA'},
 'ST307Q06JA': {'ST307Q06JA'},
 'ST307Q07JA': {'ST307Q07JA'},
 'ST307Q08JA': {'ST307Q08JA'},
 'ST307Q09JA': {'ST307Q09JA'},
 'ST307Q10JA': {'ST307Q10JA'},
 'ST309Q01JA': {'ST309Q01JA'},
 'ST309Q02JA': {'ST309Q02JA'},
 'ST309Q03JA': {'ST309Q03JA'},
 'ST309Q04JA': {'ST309Q04JA'},
 'ST309Q05JA': {'ST309Q05JA'},
 'ST309Q06JA': {'ST309Q06JA'},
 'ST309Q07JA': {'ST309Q07JA'},
 'ST309Q08JA': {'ST309Q08JA'},
 'ST309Q09JA': {'ST309Q09JA'},
 'ST309Q10JA': {'ST309Q10JA'},
 'ST301Q01JA': {'ST301Q01JA'},
 'ST301Q02JA': {'ST301Q02JA'},
 'ST301Q03JA': {'ST301Q03JA'},
 'ST301Q04JA': {'ST301Q04JA'},
 'ST301Q05JA': {'ST301Q05JA'},
 'ST301Q06JA': {'ST301Q06JA'},
 'ST301Q07JA': {'ST301Q07JA'},
 'ST301Q08JA': {'ST301Q08JA'},
 'ST301Q09JA': {'ST301Q09JA'},
 'ST301Q10JA': {'ST301Q10JA'},
 'ST343Q01JA': {'ST343Q01JA'},
 'ST343Q02JA': {'ST343Q02JA'},
 'ST343Q03JA': {'ST343Q03JA'},
 'ST343Q04JA': {'ST343Q04JA'},
 'ST343Q05JA': {'ST343Q05JA'},
 'ST343Q06JA': {'ST343Q06JA'},
 'ST343Q07JA': {'ST343Q07JA'},
 'ST343Q08JA': {'ST343Q08JA'},
 'ST343Q09JA': {'ST343Q09JA'},
 'ST343Q10JA': {'ST343Q10JA'},
 'ST311Q01JA': {'ST311Q01JA'},
 'ST311Q02JA': {'ST311Q02JA'},
 'ST311Q03JA': {'ST311Q03JA'},
 'ST311Q04JA': {'ST311Q04JA'},
 'ST311Q05JA': {'ST311Q05JA'},
 'ST311Q06JA': {'ST311Q06JA'},
 'ST311Q07JA': {'ST311Q07JA'},
 'ST311Q08JA': {'ST311Q08JA'},
 'ST311Q09JA': {'ST311Q09JA'},
 'ST311Q10JA': {'ST311Q10JA'},
 'ST315Q01JA': {'ST315Q01JA'},
 'ST315Q02JA': {'ST315Q02JA'},
 'ST315Q03JA': {'ST315Q03JA'},
 'ST315Q04JA': {'ST315Q04JA'},
 'ST315Q05JA': {'ST315Q05JA'},
 'ST315Q06JA': {'ST315Q06JA'},
 'ST315Q07JA': {'ST315Q07JA'},
 'ST315Q08JA': {'ST315Q08JA'},
 'ST315Q09JA': {'ST315Q09JA'},
 'ST315Q10JA': {'ST315Q10JA'},
 'ST303Q01JA': {'ST303Q01JA'},
 'ST303Q02JA': {'ST303Q02JA'},
 'ST303Q03JA': {'ST303Q03JA'},
 'ST303Q04JA': {'ST303Q04JA'},
 'ST303Q05JA': {'ST303Q05JA'},
 'ST303Q06JA': {'ST303Q06JA'},
 'ST303Q07JA': {'ST303Q07JA'},
 'ST303Q08JA': {'ST303Q08JA'},
 'ST305Q01JA': {'ST305Q01JA'},
 'ST305Q02JA': {'ST305Q02JA'},
 'ST305Q03JA': {'ST305Q03JA'},
 'ST305Q04JA': {'ST305Q04JA'},
 'ST305Q05JA': {'ST305Q05JA'},
 'ST305Q06JA': {'ST305Q06JA'},
 'ST305Q07JA': {'ST305Q07JA'},
 'ST305Q08JA': {'ST305Q08JA'},
 'ST305Q09JA': {'ST305Q09JA'},
 'ST305Q10JA': {'ST305Q10JA'},
 'ST345Q01JA': {'ST345Q01JA'},
 'ST345Q02JA': {'ST345Q02JA'},
 'ST345Q03JA': {'ST345Q03JA'},
 'ST345Q04JA': {'ST345Q04JA'},
 'ST345Q05JA': {'ST345Q05JA'},
 'ST345Q06JA': {'ST345Q06JA'},
 'ST345Q07JA': {'ST345Q07JA'},
 'ST345Q08JA': {'ST345Q08JA'},
 'ST345Q09JA': {'ST345Q09JA'},
 'ST345Q10JA': {'ST345Q10JA'},
 'ST313Q01JA': {'ST313Q01JA'},
 'ST313Q02JA': {'ST313Q02JA'},
 'ST313Q03JA': {'ST313Q03JA'},
 'ST313Q04JA': {'ST313Q04JA'},
 'ST313Q05JA': {'ST313Q05JA'},
 'ST313Q06JA': {'ST313Q06JA'},
 'ST313Q07JA': {'ST313Q07JA'},
 'ST313Q08JA': {'ST313Q08JA'},
 'ST313Q09JA': {'ST313Q09JA'},
 'ST313Q10JA': {'ST313Q10JA'},
 'ST263Q02JA': {'ST263Q02JA'},
 'ST263Q04JA': {'ST263Q04JA'},
 'ST263Q06JA': {'ST263Q06JA'},
 'ST016Q01NA': {'ST016Q01NA'},
 'ST059Q01TA': {'ST059Q01TA'},
 'ST059Q02JA': {'ST059Q02JA'},
 'ST296Q01JA': {'ST296Q01JA'},
 'ST296Q02JA': {'ST296Q02JA'},
 'ST296Q03JA': {'ST296Q03JA'},
 'ST296Q04JA': {'ST296Q04JA'},
 'ST272Q01JA': {'ST272Q01JA'},
 'ST273Q01JA': {'ST273Q01JA'},
 'ST273Q02JA': {'ST273Q02JA'},
 'ST273Q03JA': {'ST273Q03JA'},
 'ST273Q04JA': {'ST273Q04JA'},
 'ST273Q05JA': {'ST273Q05JA'},
 'ST273Q06JA': {'ST273Q06JA'},
 'ST273Q07JA': {'ST273Q07JA'},
 'ST270Q01JA': {'ST270Q01JA'},
 'ST270Q02JA': {'ST270Q02JA'},
 'ST270Q03JA': {'ST270Q03JA'},
 'ST270Q04JA': {'ST270Q04JA'},
 'ST285Q01JA': {'ST285Q01JA'},
 'ST285Q02JA': {'ST285Q02JA'},
 'ST285Q03JA': {'ST285Q03JA'},
 'ST285Q04JA': {'ST285Q04JA'},
 'ST285Q05JA': {'ST285Q05JA'},
 'ST285Q06JA': {'ST285Q06JA'},
 'ST285Q07JA': {'ST285Q07JA'},
 'ST285Q08JA': {'ST285Q08JA'},
 'ST285Q09JA': {'ST285Q09JA'},
 'ST283Q01JA': {'ST283Q01JA'},
 'ST283Q02JA': {'ST283Q02JA'},
 'ST283Q03JA': {'ST283Q03JA'},
 'ST283Q04JA': {'ST283Q04JA'},
 'ST283Q05JA': {'ST283Q05JA'},
 'ST283Q06JA': {'ST283Q06JA'},
 'ST283Q07JA': {'ST283Q07JA'},
 'ST283Q08JA': {'ST283Q08JA'},
 'ST283Q09JA': {'ST283Q09JA'},
 'ST275Q01WA': {'ST275Q01WA'},
 'ST275Q02WA': {'ST275Q02WA'},
 'ST275Q03WA': {'ST275Q03WA'},
 'ST275Q04WA': {'ST275Q04WA'},
 'ST275Q05WA': {'ST275Q05WA'},
 'ST275Q06WA': {'ST275Q06WA'},
 'ST275Q07WA': {'ST275Q07WA'},
 'ST275Q08WA': {'ST275Q08WA'},
 'ST275Q09WA': {'ST275Q09WA'},
 'ST276Q01JA': {'ST276Q01JA'},
 'ST276Q02JA': {'ST276Q02JA'},
 'ST276Q03JA': {'ST276Q03JA'},
 'ST276Q04JA': {'ST276Q04JA'},
 'ST276Q05JA': {'ST276Q05JA'},
 'ST276Q06JA': {'ST276Q06JA'},
 'ST276Q07JA': {'ST276Q07JA'},
 'ST276Q08JA': {'ST276Q08JA'},
 'ST276Q09JA': {'ST276Q09JA'},
 'ST276Q10JA': {'ST276Q10JA'},
 'ST268Q01JA': {'ST268Q01JA'},
 'ST268Q02JA': {'ST268Q02JA'},
 'ST268Q03JA': {'ST268Q03JA'},
 'ST268Q04JA': {'ST268Q04JA'},
 'ST268Q05JA': {'ST268Q05JA'},
 'ST268Q06JA': {'ST268Q06JA'},
 'ST268Q07JA': {'ST268Q07JA'},
 'ST268Q08JA': {'ST268Q08JA'},
 'ST268Q09JA': {'ST268Q09JA'},
 'ST290Q01WA': {'ST290Q01WA'},
 'ST290Q02WA': {'ST290Q02WA'},
 'ST290Q03WA': {'ST290Q03WA'},
 'ST290Q04WA': {'ST290Q04WA'},
 'ST290Q05WA': {'ST290Q05WA'},
 'ST290Q06WA': {'ST290Q06WA'},
 'ST290Q07WA': {'ST290Q07WA'},
 'ST290Q08WA': {'ST290Q08WA'},
 'ST290Q09WA': {'ST290Q09WA'},
 'ST291Q01JA': {'ST291Q01JA'},
 'ST291Q02JA': {'ST291Q02JA'},
 'ST291Q03JA': {'ST291Q03JA'},
 'ST291Q04JA': {'ST291Q04JA'},
 'ST291Q05JA': {'ST291Q05JA'},
 'ST291Q06JA': {'ST291Q06JA'},
 'ST291Q07JA': {'ST291Q07JA'},
 'ST291Q08JA': {'ST291Q08JA'},
 'ST291Q09JA': {'ST291Q09JA'},
 'ST291Q10JA': {'ST291Q10JA'},
 'ST289Q01WA': {'ST289Q01WA'},
 'ST289Q02JA': {'ST289Q02JA'},
 'ST289Q03WA': {'ST289Q03WA'},
 'ST289Q04JA': {'ST289Q04JA'},
 'ST289Q05WA': {'ST289Q05WA'},
 'ST289Q06JA': {'ST289Q06JA'},
 'ST289Q07JA': {'ST289Q07JA'},
 'ST289Q08WA': {'ST289Q08WA'},
 'ST289Q09WA': {'ST289Q09WA'},
 'ST289Q10WA': {'ST289Q10WA'},
 'ST289Q11WA': {'ST289Q11WA'},
 'ST289Q14JA': {'ST289Q14JA'},
 'ST293Q01JA': {'ST293Q01JA'},
 'ST293Q02JA': {'ST293Q02JA'},
 'ST293Q03JA': {'ST293Q03JA'},
 'ST293Q04JA': {'ST293Q04JA'},
 'ST293Q05JA': {'ST293Q05JA'},
 'ST293Q06JA': {'ST293Q06JA'},
 'ST293Q07JA': {'ST293Q07JA'},
 'ST293Q08JA': {'ST293Q08JA'},
 'ST293Q09JA': {'ST293Q09JA'},
 'ST292Q01JA': {'ST292Q01JA'},
 'ST292Q02JA': {'ST292Q02JA'},
 'ST292Q03JA': {'ST292Q03JA'},
 'ST292Q04JA': {'ST292Q04JA'},
 'ST292Q05JA': {'ST292Q05JA'},
 'ST292Q06JA': {'ST292Q06JA'},
 'ST297Q01JA': {'ST297Q01JA'},
 'ST297Q03JA': {'ST297Q03JA'},
 'ST297Q05JA': {'ST297Q05JA'},
 'ST297Q06JA': {'ST297Q06JA'},
 'ST297Q07JA': {'ST297Q07JA'},
 'ST297Q09JA': {'ST297Q09JA'},
 'ST300Q01JA': {'ST300Q01JA'},
 'ST300Q02JA': {'ST300Q02JA'},
 'ST300Q03JA': {'ST300Q03JA'},
 'ST300Q04JA': {'ST300Q04JA'},
 'ST300Q05JA': {'ST300Q05JA'},
 'ST300Q06JA': {'ST300Q06JA'},
 'ST300Q07JA': {'ST300Q07JA'},
 'ST300Q08JA': {'ST300Q08JA'},
 'ST300Q09JA': {'ST300Q09JA'},
 'ST300Q10JA': {'ST300Q10JA'},
 'ST327Q01JA': {'ST327Q01JA'},
 'ST327Q02JA': {'ST327Q02JA'},
 'ST327Q03JA': {'ST327Q03JA'},
 'ST327Q04JA': {'ST327Q04JA'},
 'ST327Q05JA': {'ST327Q05JA'},
 'ST327Q06JA': {'ST327Q06JA'},
 'ST327Q07JA': {'ST327Q07JA'},
 'ST327Q08JA': {'ST327Q08JA'},
 'ST330Q01WA': {'ST330Q01WA'},
 'ST330Q02WA': {'ST330Q02WA'},
 'ST330Q03WA': {'ST330Q03WA'},
 'ST330Q04WA': {'ST330Q04WA'},
 'ST330Q05WA': {'ST330Q05WA'},
 'ST330Q06WA': {'ST330Q06WA'},
 'ST330Q07WA': {'ST330Q07WA'},
 'ST330Q08WA': {'ST330Q08WA'},
 'ST330Q09WA': {'ST330Q09WA'},
 'ST330Q11WA': {'ST330Q11WA'},
 'ST330D10WA': {'ST330D10WA'},
 'ST324Q02JA': {'ST324Q02JA'},
 'ST324Q04JA': {'ST324Q04JA'},
 'ST324Q05JA': {'ST324Q05JA'},
 'ST324Q07JA': {'ST324Q07JA'},
 'ST324Q10JA': {'ST324Q10JA'},
 'ST324Q11JA': {'ST324Q11JA'},
 'ST324Q12JA': {'ST324Q12JA'},
 'ST324Q13JA': {'ST324Q13JA'},
 'ST324Q14JA': {'ST324Q14JA'},
 'ST347Q01JA': {'ST347Q01JA'},
 'ST347Q02JA': {'ST347Q02JA'},
 'ST348Q01JA': {'ST348Q01JA'},
 'ST348Q02JA': {'ST348Q02JA'},
 'ST348Q03JA': {'ST348Q03JA'},
 'ST348Q04JA': {'ST348Q04JA'},
 'ST348Q05JA': {'ST348Q05JA'},
 'ST348Q06JA': {'ST348Q06JA'},
 'ST348Q07JA': {'ST348Q07JA'},
 'ST348Q08JA': {'ST348Q08JA'},
 'ST349Q01JA': {'ST349Q01JA'},
 'ST350Q01JA': {'ST350Q01JA'},
 'ST351Q01JA': {'ST351Q01JA'},
 'ST351Q02JA': {'ST351Q02JA'},
 'ST351Q03JA': {'ST351Q03JA'},
 'ST351Q04JA': {'ST351Q04JA'},
 'ST351Q05JA': {'ST351Q05JA'},
 'ST351Q06JA': {'ST351Q06JA'},
 'ST351Q07JA': {'ST351Q07JA'},
 'ST351Q08JA': {'ST351Q08JA'},
 'ST352Q01JA': {'ST352Q01JA'},
 'ST352Q02JA': {'ST352Q02JA'},
 'ST352Q03JA': {'ST352Q03JA'},
 'ST352Q04JA': {'ST352Q04JA'},
 'ST352Q05JA': {'ST352Q05JA'},
 'ST352Q06JA': {'ST352Q06JA'},
 'ST352Q07JA': {'ST352Q07JA'},
 'ST352Q08JA': {'ST352Q08JA'},
 'ST353Q01JA': {'ST353Q01JA'},
 'ST353Q02JA': {'ST353Q02JA'},
 'ST353Q03JA': {'ST353Q03JA'},
 'ST353Q04JA': {'ST353Q04JA'},
 'ST353Q05JA': {'ST353Q05JA'},
 'ST353Q06JA': {'ST353Q06JA'},
 'ST353Q07JA': {'ST353Q07JA'},
 'ST353Q08JA': {'ST353Q08JA'},
 'ST354Q01JA': {'ST354Q01JA'},
 'ST354Q02JA': {'ST354Q02JA'},
 'ST354Q03JA': {'ST354Q03JA'},
 'ST354Q04JA': {'ST354Q04JA'},
 'ST354Q05JA': {'ST354Q05JA'},
 'ST354Q06JA': {'ST354Q06JA'},
 'ST354Q07JA': {'ST354Q07JA'},
 'ST354Q08JA': {'ST354Q08JA'},
 'ST354Q09JA': {'ST354Q09JA'},
 'ST354Q10JA': {'ST354Q10JA'},
 'ST355Q01JA': {'ST355Q01JA'},
 'ST355Q02JA': {'ST355Q02JA'},
 'ST355Q03JA': {'ST355Q03JA'},
 'ST355Q04JA': {'ST355Q04JA'},
 'ST355Q05JA': {'ST355Q05JA'},
 'ST355Q06JA': {'ST355Q06JA'},
 'ST355Q07JA': {'ST355Q07JA'},
 'ST355Q08JA': {'ST355Q08JA'},
 'ST356Q01JA': {'ST356Q01JA'},
 'ST331Q01JA': {'ST331Q01JA'},
 'ST331Q02JA': {'ST331Q02JA'},
 'ST331Q03JA': {'ST331Q03JA'},
 'IC170Q01JA': {'IC170Q01JA'},
 'IC170Q02JA': {'IC170Q02JA'},
 'IC170Q03JA': {'IC170Q03JA'},
 'IC170Q04JA': {'IC170Q04JA'},
 'IC170Q05JA': {'IC170Q05JA'},
 'IC170Q06JA': {'IC170Q06JA'},
 'IC170Q07JA': {'IC170Q07JA'},
 'IC171Q01JA': {'IC171Q01JA'},
 'IC171Q02JA': {'IC171Q02JA'},
 'IC171Q03JA': {'IC171Q03JA'},
 'IC171Q04JA': {'IC171Q04JA'},
 'IC171Q05JA': {'IC171Q05JA'},
 'IC171Q06JA': {'IC171Q06JA'},
 'IC172Q01JA': {'IC172Q01JA'},
 'IC172Q02JA': {'IC172Q02JA'},
 'IC172Q03JA': {'IC172Q03JA'},
 'IC172Q04JA': {'IC172Q04JA'},
 'IC172Q05JA': {'IC172Q05JA'},
 'IC172Q06JA': {'IC172Q06JA'},
 'IC172Q07JA': {'IC172Q07JA'},
 'IC172Q08JA': {'IC172Q08JA'},
 'IC172Q09JA': {'IC172Q09JA'},
 'IC173Q01JA': {'IC173Q01JA'},
 'IC173Q02JA': {'IC173Q02JA'},
 'IC173Q03JA': {'IC173Q03JA'},
 'IC173Q04JA': {'IC173Q04JA'},
 'IC174Q01JA': {'IC174Q01JA'},
 'IC174Q02JA': {'IC174Q02JA'},
 'IC174Q03JA': {'IC174Q03JA'},
 'IC174Q04JA': {'IC174Q04JA'},
 'IC174Q05JA': {'IC174Q05JA'},
 'IC174Q06JA': {'IC174Q06JA'},
 'IC174Q07JA': {'IC174Q07JA'},
 'IC174Q08JA': {'IC174Q08JA'},
 'IC174Q09JA': {'IC174Q09JA'},
 'IC174Q10JA': {'IC174Q10JA'},
 'IC175Q01JA': {'IC175Q01JA'},
 'IC175Q02JA': {'IC175Q02JA'},
 'IC175Q03JA': {'IC175Q03JA'},
 'IC175Q05JA': {'IC175Q05JA'},
 'IC176Q01JA': {'IC176Q01JA'},
 'IC176Q02JA': {'IC176Q02JA'},
 'IC176Q03JA': {'IC176Q03JA'},
 'IC176Q04JA': {'IC176Q04JA'},
 'IC176Q05JA': {'IC176Q05JA'},
 'IC176Q06JA': {'IC176Q06JA'},
 'IC176Q07JA': {'IC176Q07JA'},
 'IC176Q08JA': {'IC176Q08JA'},
 'IC184Q01JA': {'IC184Q01JA'},
 'IC184Q02JA': {'IC184Q02JA'},
 'IC184Q03JA': {'IC184Q03JA'},
 'IC184Q04JA': {'IC184Q04JA'},
 'IC177Q01JA': {'IC177Q01JA'},
 'IC177Q02JA': {'IC177Q02JA'},
 'IC177Q03JA': {'IC177Q03JA'},
 'IC177Q04JA': {'IC177Q04JA'},
 'IC177Q05JA': {'IC177Q05JA'},
 'IC177Q06JA': {'IC177Q06JA'},
 'IC177Q07JA': {'IC177Q07JA'},
 'IC178Q01JA': {'IC178Q01JA'},
 'IC178Q02JA': {'IC178Q02JA'},
 'IC178Q03JA': {'IC178Q03JA'},
 'IC178Q04JA': {'IC178Q04JA'},
 'IC178Q05JA': {'IC178Q05JA'},
 'IC178Q06JA': {'IC178Q06JA'},
 'IC178Q07JA': {'IC178Q07JA'},
 'IC179Q01JA': {'IC179Q01JA'},
 'IC179Q02JA': {'IC179Q02JA'},
 'IC179Q03JA': {'IC179Q03JA'},
 'IC179Q04JA': {'IC179Q04JA'},
 'IC179Q05JA': {'IC179Q05JA'},
 'IC179Q06JA': {'IC179Q06JA'},
 'IC180Q01JA': {'IC180Q01JA'},
 'IC180Q02JA': {'IC180Q02JA'},
 'IC180Q03JA': {'IC180Q03JA'},
 'IC180Q04JA': {'IC180Q04JA'},
 'IC180Q05JA': {'IC180Q05JA'},
 'IC180Q06JA': {'IC180Q06JA'},
 'IC180Q07JA': {'IC180Q07JA'},
 'IC180Q08JA': {'IC180Q08JA'},
 'IC181Q01JA': {'IC181Q01JA'},
 'IC181Q02JA': {'IC181Q02JA'},
 'IC181Q03JA': {'IC181Q03JA'},
 'IC181Q04JA': {'IC181Q04JA'},
 'IC182Q01JA': {'IC182Q01JA'},
 'IC182Q02JA': {'IC182Q02JA'},
 'IC182Q03JA': {'IC182Q03JA'},
 'IC183Q01JA': {'IC183Q01JA'},
 'IC183Q02JA': {'IC183Q02JA'},
 'IC183Q03JA': {'IC183Q03JA'},
 'IC183Q04JA': {'IC183Q04JA'},
 'IC183Q05JA': {'IC183Q05JA'},
 'IC183Q07JA': {'IC183Q07JA'},
 'IC183Q08JA': {'IC183Q08JA'},
 'IC183Q09JA': {'IC183Q09JA'},
 'IC183Q10JA': {'IC183Q10JA'},
 'IC183Q12JA': {'IC183Q12JA'},
 'IC183Q13JA': {'IC183Q13JA'},
 'IC183Q14JA': {'IC183Q14JA'},
 'IC183Q15JA': {'IC183Q15JA'},
 'IC183Q16JA': {'IC183Q16JA'},
 'EFFORT1': {'EFFORT1'},
 'EFFORT2': {'EFFORT2'},
 'OCOD1': {'OCOD1'},
 'OCOD2': {'OCOD2'},
 'OCOD3': {'OCOD3'},
 'PROGN': {'PROGN'},
 'AGE': {'AGE'},
 'GRADE': {'GRADE'},
 'ISCEDP': {'ISCEDP'},
 'IMMIG': {'IMMIG'},
 'COBN_S': {'COBN_S'},
 'COBN_M': {'COBN_M'},
 'COBN_F': {'COBN_F'},
 'LANGN': {'LANGN'},
 'REPEAT': {'REPEAT'},
 'MISSSC': {'MISSSC'},
 'SKIPPING': {'SKIPPING'},
 'TARDYSD': {'TARDYSD'},
 'EXERPRAC': {'EXERPRAC'},
 'STUDYHMW': {'STUDYHMW'},
 'WORKPAY': {'WORKPAY'},
 'WORKHOME': {'WORKHOME'},
 'EXPECEDU': {'EXPECEDU'},
 'MATHPREF': {'MATHPREF'},
 'MATHEASE': {'MATHEASE'},
 'MATHMOT': {'MATHMOT'},
 'DURECEC': {'DURECEC'},
 'BSMJ': {'BSMJ'},
 'SISCO': {'SISCO'},
 'RELATST': {'RELATST'},
 'BELONG': {'BELONG'},
 'BULLIED': {'BULLIED'},
 'FEELSAFE': {'FEELSAFE'},
 'SCHRISK': {'SCHRISK'},
 'PERSEVAGR': {'PERSEVAGR'},
 'CURIOAGR': {'CURIOAGR'},
 'COOPAGR': {'COOPAGR'},
 'EMPATAGR': {'EMPATAGR'},
 'ASSERAGR': {'ASSERAGR'},
 'STRESAGR': {'STRESAGR'},
 'EMOCOAGR': {'EMOCOAGR'},
 'INFOSEEK': {'INFOSEEK'},
 'FAMSUP': {'FAMSUP'},
 'DISCLIM': {'DISCLIM'},
 'TEACHSUP': {'TEACHSUP'},
 'COGACRCO': {'COGACRCO'},
 'COGACMCO': {'COGACMCO'},
 'EXPOFA': {'EXPOFA'},
 'EXPO21ST': {'EXPO21ST'},
 'MATHEFF': {'MATHEFF'},
 'MATHEF21': {'MATHEF21'},
 'FAMCON': {'FAMCON'},
 'ANXMAT': {'ANXMAT'},
 'MATHPERS': {'MATHPERS'},
 'SCHSUST': {'SCHSUST'},
 'LEARRES': {'LEARRES'},
 'PROBSELF': {'PROBSELF'},
 'FAMSUPSL': {'FAMSUPSL'},
 'FEELLAH': {'FEELLAH'},
 'SDLEFF': {'SDLEFF'},
 'MISCED': {'MISCED'},
 'FISCED': {'FISCED'},
 'HISCED': {'HISCED'},
 'PAREDINT': {'PAREDINT'},
 'BMMJ1': {'BMMJ1'},
 'BFMJ2': {'BFMJ2'},
 'HISEI': {'HISEI'},
 'ICTRES': {'ICTRES'},
 'HOMEPOS': {'HOMEPOS'},
 'ESCS': {'ESCS'},
 'ICTSCH': {'ICTSCH'},
 'ICTAVSCH': {'ICTAVSCH'},
 'ICTHOME': {'ICTHOME'},
 'ICTAVHOM': {'ICTAVHOM'},
 'ICTQUAL': {'ICTQUAL'},
 'ICTSUBJ': {'ICTSUBJ'},
 'ICTENQ': {'ICTENQ'},
 'ICTFEED': {'ICTFEED'},
 'ICTOUT': {'ICTOUT'},
 'ICTWKDY': {'ICTWKDY'},
 'ICTWKEND': {'ICTWKEND'},
 'ICTREG': {'ICTREG'},
 'ICTINFO': {'ICTINFO'},
 'ICTDISTR': {'ICTDISTR'},
 'ICTEFFIC': {'ICTEFFIC'},
 'W_FSTUWT': {'W_FSTUWT'},
 'W_FSTURWT1': {'W_FSTURWT1'},
 'W_FSTURWT2': {'W_FSTURWT2'},
 'W_FSTURWT3': {'W_FSTURWT3'},
 'W_FSTURWT4': {'W_FSTURWT4'},
 'W_FSTURWT5': {'W_FSTURWT5'},
 'W_FSTURWT6': {'W_FSTURWT6'},
 'W_FSTURWT7': {'W_FSTURWT7'},
 'W_FSTURWT8': {'W_FSTURWT8'},
 'W_FSTURWT9': {'W_FSTURWT9'},
 'W_FSTURWT10': {'W_FSTURWT10'},
 'W_FSTURWT11': {'W_FSTURWT11'},
 'W_FSTURWT12': {'W_FSTURWT12'},
 'W_FSTURWT13': {'W_FSTURWT13'},
 'W_FSTURWT14': {'W_FSTURWT14'},
 'W_FSTURWT15': {'W_FSTURWT15'},
 'W_FSTURWT16': {'W_FSTURWT16'},
 'W_FSTURWT17': {'W_FSTURWT17'},
 'W_FSTURWT18': {'W_FSTURWT18'},
 'W_FSTURWT19': {'W_FSTURWT19'},
 'W_FSTURWT20': {'W_FSTURWT20'},
 'W_FSTURWT21': {'W_FSTURWT21'},
 'W_FSTURWT22': {'W_FSTURWT22'},
 'W_FSTURWT23': {'W_FSTURWT23'},
 'W_FSTURWT24': {'W_FSTURWT24'},

In [ ]:
###pisa_school_only_tokens['Slovak Republic'].add('Slovak Republic')


###pisa_school_only_tokens

In [ ]:
"""pisa2022_avr_scores_only = set(pisa2022_avr_scores_df['Country/Region']) - set(pisa2022_df['Country/Region'])
candidates = {}

for pisa_school_region, tokens in pisa_school_only_tokens.items():
    for token in tokens:
        for pisa_scores_region in pisa2022_avr_scores_only:
            if token in pisa_scores_region:
                candidates[pisa_school_region] = pisa_scores_region
            
candidates"""

In [ ]:
"""pisa_scores_only = set(pisa2022_avr_scores_df['Country/Region']) - set(pisa2022_df['Country/Region'])
candidates = {}

for pisa_school_region, tokens in pisa_school_only_tokens.items():
    for token in tokens:
        for pisa_scores_region in pisa_scores_only:
            if token in pisa_scores_region:
                candidates[pisa_school_region] = pisa_scores_region
            
candidates"""

In [ ]:
for pisa_school_region, pisa_scores_region in candidates.items():
    pisa2022_df.loc[pisa2022_df['Country/Region'] == pisa_school_region, 'Country/Region'] = pisa_scores_region
    
pisa2022_df

In [ ]:
##df_pisa2022 = pisa2022_school_df.merge(pisa2022_avr_scores_df, left_on = 'Country/Region', right_on = 'Country/Region', how = 'left')

#df_pisa2022

In [ ]:
slovak_data = pisa2022_school_df[pisa2022_school_df['Country/Region'].str.contains('Cambodia', case=False)]

In [ ]:
unique_countries = pisa2022_school_df['Country/Region'].nunique()
unique_countries

In [ ]:
pisa2022_school_df.to_csv('pisa2022.csv', index=False)

In [ ]:
asdsadad =

Math Literacy

In [ ]:
df_pisa2022[['PV1MATH','PV2MATH','PV3MATH', 'PV4MATH', 'PV5MATH','PV6MATH','PV7MATH','PV8MATH', 'PV9MATH', 'PV10MATH']].describe()
df_pisa2022['Avg_Math_Literacy'] = df_pisa2022[['PV1MATH','PV2MATH','PV3MATH', 'PV4MATH', 'PV5MATH','PV6MATH','PV7MATH','PV8MATH', 'PV9MATH', 'PV10MATH']].mean(axis=1)

In [ ]:
df_pisa2022[['PV1SCIE','PV2SCIE','PV3SCIE','PV4SCIE','PV5SCIE','PV6SCIE','PV7SCIE','PV8SCIE','PV9SCIE','PV10SCIE']].describe()
df_pisa2022['Avg_Scientific_Literacy'] = df_pisa2022[['PV1SCIE','PV2SCIE','PV3SCIE','PV4SCIE','PV5SCIE','PV6SCIE','PV7SCIE','PV8SCIE','PV9SCIE','PV10SCIE']].mean(axis=1)

In [ ]:
df_pisa2022[['PV1READ','PV2READ','PV3READ', 'PV4READ', 'PV5READ','PV6READ','PV7READ','PV8READ', 'PV9READ', 'PV10READ']].describe()
df_pisa2022['Avg_Reading_Literacy'] = df_pisa2022[['PV1READ','PV2READ','PV3READ', 'PV4READ', 'PV5READ','PV6READ','PV7READ','PV8READ', 'PV9READ', 'PV10READ']].mean(axis=1)

In [ ]:
df_pisa2022['Overall_Literacy'] = df_pisa2022[['Avg_Math_Literacy','Avg_Scientific_Literacy','Avg_Reading_Literacy']].mean(axis=1)
df_pisa2022[['Avg_Math_Literacy','Avg_Scientific_Literacy','Avg_Reading_Literacy','Overall_Literacy']];

In [ ]:
pisa_analysis_df = df_pisa2022[['CNTSCHID','CNTSTUID', 'Country/Region', 'OECD', 'ST001D01T','ST004D01T','ST250Q04JA','ST250Q05JA','ST307Q10JA','ST034Q06TA','ST294Q02JA','HISCED','Avg_Math_Literacy','Avg_Scientific_Literacy','Avg_Reading_Literacy','Overall_Literacy', 'Average_Score']]
pisa_analysis_df

In [ ]:
pisa_analysis_df.rename(columns = {'CNTSCHID':'School_ID',
                          'CNTSTUID':'Student_ID',
                          'ST001D01T' : 'Student_Grade',
                          'ST004D01T' : 'Gender',
                          'ST250Q04JA' : 'Smartphone_with_internet',
                          'ST250Q05JA' : 'Internet_access',
                          'ST307Q10JA' : 'Perseverance_Give_up_easily',
                          'ST034Q06TA' : 'Feel_lonely_at_school',  
                          'ST294Q02JA' : 'Study_for_school_or_homework',
                          'HISCED'  : 'Highest_educational_level_parents'
                          }, inplace = True)
pisa_analysis_df

In [ ]:
pisa_analysis_df.isnull().sum().sort_values(ascending=False)/613744*100;

In [ ]:
pisa_analysis_df.isnull().sum().sort_values(ascending=False);

In [ ]:
pisa_analysis_df['Study_for_school_or_homework'].unique()

In [ ]:
pisa_analysis_df['OECD'].replace({0: 'NON-OECD', 1: 'OECD'}, inplace=True)
pisa_analysis_df['Gender'].replace({1: 'Female', 2: 'Male'}, inplace=True)
pisa_analysis_df['Smartphone_with_internet'].replace({1: 'Yes', 2: 'No'}, inplace=True)
pisa_analysis_df['Internet_access'].replace({1: 'Yes', 2: 'No'}, inplace=True)
pisa_analysis_df['Perseverance_Give_up_easily'].replace({'Strongly disagree': 'Strongly Disagree', 2: 'Disagree', 3: 'Neither agree nor disagree', 4: 'Agree', 5: 'Strongly Agree'}, inplace=True)
pisa_analysis_df['Feel_lonely_at_school'].replace({1: 'Strongly Agree', 2: 'Agree', 3: 'Disagree', 'Strongly disagreeree': 'Strongly Disagree'}, inplace=True)
pisa_analysis_df['Study_for_school_or_homework'].replace({1: '0 days', 2: '1 days', 3: '2 days', 4: '3 days', 5: '4 days', 6: '5 or more days'}, inplace=True)

In [ ]:
df_pisa2022_final = pisa_analysis_df.dropna()
df_pisa2022_final.shape

In [ ]:
print('The cleaned dataframe is composed of only',(203378)/613744 *100,'% of the original dataset.')

In [ ]:
df_pisa2022_final

Fixing datatype

In [ ]:
df_pisa2022_final['OECD'] = df_pisa2022_final.OECD.astype('category')
df_pisa2022_final['OECD'].dtypes

In [ ]:
df_pisa2022_final['Gender'] = df_pisa2022_final.Gender.astype('category')
df_pisa2022_final['Student_Grade'] = df_pisa2022_final.Student_Grade.astype('float64')
df_pisa2022_final['Perseverance_Give_up_easily'] = df_pisa2022_final.Perseverance_Give_up_easily.astype('category')
df_pisa2022_final['Smartphone_with_internet'] = df_pisa2022_final.Smartphone_with_internet.astype('category')
df_pisa2022_final['Internet_access'] = df_pisa2022_final.Internet_access.astype('category')
df_pisa2022_final['Feel_lonely_at_school'] = df_pisa2022_final.Feel_lonely_at_school.astype('category')
df_pisa2022_final['Study_for_school_or_homework'] = df_pisa2022_final.Study_for_school_or_homework.astype('category')

In [ ]:
df_pisa2022_final.info()

In [ ]:
plt.figure(figsize=(15,16))
sb.countplot(data=df_pisa2022_final, y= 'Country/Region', color='darkblue', order = df_pisa2022_final['Country/Region'].value_counts(ascending=False).index);

In [ ]:
pisa2022_df.to_csv('pisa2022.csv', index=False)